// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cloud_wallet.proto

package cloud_wallet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 通用消息回复组件
type CommonResp struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResp) Reset()         { *m = CommonResp{} }
func (m *CommonResp) String() string { return proto.CompactTextString(m) }
func (*CommonResp) ProtoMessage()    {}
func (*CommonResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{0}
}

func (m *CommonResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResp.Unmarshal(m, b)
}
func (m *CommonResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResp.Marshal(b, m, deterministic)
}
func (m *CommonResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResp.Merge(m, src)
}
func (m *CommonResp) XXX_Size() int {
	return xxx_messageInfo_CommonResp.Size(m)
}
func (m *CommonResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResp.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResp proto.InternalMessageInfo

func (m *CommonResp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CommonResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// 1. 获取云账户信息
type UserNcountAccountReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserNcountAccountReq) Reset()         { *m = UserNcountAccountReq{} }
func (m *UserNcountAccountReq) String() string { return proto.CompactTextString(m) }
func (*UserNcountAccountReq) ProtoMessage()    {}
func (*UserNcountAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{1}
}

func (m *UserNcountAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserNcountAccountReq.Unmarshal(m, b)
}
func (m *UserNcountAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserNcountAccountReq.Marshal(b, m, deterministic)
}
func (m *UserNcountAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserNcountAccountReq.Merge(m, src)
}
func (m *UserNcountAccountReq) XXX_Size() int {
	return xxx_messageInfo_UserNcountAccountReq.Size(m)
}
func (m *UserNcountAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserNcountAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserNcountAccountReq proto.InternalMessageInfo

func (m *UserNcountAccountReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserNcountAccountResp struct {
	Step                 uint32      `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	RealAuth             uint32      `protobuf:"varint,2,opt,name=realAuth,proto3" json:"realAuth,omitempty"`
	IdCard               string      `protobuf:"bytes,3,opt,name=idCard,proto3" json:"idCard,omitempty"`
	RealName             string      `protobuf:"bytes,4,opt,name=realName,proto3" json:"realName,omitempty"`
	AccountStatus        uint32      `protobuf:"varint,5,opt,name=accountStatus,proto3" json:"accountStatus,omitempty"`
	CommonResp           *CommonResp `protobuf:"bytes,6,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserNcountAccountResp) Reset()         { *m = UserNcountAccountResp{} }
func (m *UserNcountAccountResp) String() string { return proto.CompactTextString(m) }
func (*UserNcountAccountResp) ProtoMessage()    {}
func (*UserNcountAccountResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{2}
}

func (m *UserNcountAccountResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserNcountAccountResp.Unmarshal(m, b)
}
func (m *UserNcountAccountResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserNcountAccountResp.Marshal(b, m, deterministic)
}
func (m *UserNcountAccountResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserNcountAccountResp.Merge(m, src)
}
func (m *UserNcountAccountResp) XXX_Size() int {
	return xxx_messageInfo_UserNcountAccountResp.Size(m)
}
func (m *UserNcountAccountResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserNcountAccountResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserNcountAccountResp proto.InternalMessageInfo

func (m *UserNcountAccountResp) GetStep() uint32 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *UserNcountAccountResp) GetRealAuth() uint32 {
	if m != nil {
		return m.RealAuth
	}
	return 0
}

func (m *UserNcountAccountResp) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func (m *UserNcountAccountResp) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *UserNcountAccountResp) GetAccountStatus() uint32 {
	if m != nil {
		return m.AccountStatus
	}
	return 0
}

func (m *UserNcountAccountResp) GetCommonResp() *CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

// 3. 检查用户的余额
type UserAccountBalanceReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAccountBalanceReq) Reset()         { *m = UserAccountBalanceReq{} }
func (m *UserAccountBalanceReq) String() string { return proto.CompactTextString(m) }
func (*UserAccountBalanceReq) ProtoMessage()    {}
func (*UserAccountBalanceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{3}
}

func (m *UserAccountBalanceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAccountBalanceReq.Unmarshal(m, b)
}
func (m *UserAccountBalanceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAccountBalanceReq.Marshal(b, m, deterministic)
}
func (m *UserAccountBalanceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAccountBalanceReq.Merge(m, src)
}
func (m *UserAccountBalanceReq) XXX_Size() int {
	return xxx_messageInfo_UserAccountBalanceReq.Size(m)
}
func (m *UserAccountBalanceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAccountBalanceReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserAccountBalanceReq proto.InternalMessageInfo

func (m *UserAccountBalanceReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UserAccountBalanceResp struct {
	MainBalance          int64       `protobuf:"varint,1,opt,name=mainBalance,proto3" json:"mainBalance,omitempty"`
	CommonResp           *CommonResp `protobuf:"bytes,2,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserAccountBalanceResp) Reset()         { *m = UserAccountBalanceResp{} }
func (m *UserAccountBalanceResp) String() string { return proto.CompactTextString(m) }
func (*UserAccountBalanceResp) ProtoMessage()    {}
func (*UserAccountBalanceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{4}
}

func (m *UserAccountBalanceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAccountBalanceResp.Unmarshal(m, b)
}
func (m *UserAccountBalanceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAccountBalanceResp.Marshal(b, m, deterministic)
}
func (m *UserAccountBalanceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAccountBalanceResp.Merge(m, src)
}
func (m *UserAccountBalanceResp) XXX_Size() int {
	return xxx_messageInfo_UserAccountBalanceResp.Size(m)
}
func (m *UserAccountBalanceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAccountBalanceResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserAccountBalanceResp proto.InternalMessageInfo

func (m *UserAccountBalanceResp) GetMainBalance() int64 {
	if m != nil {
		return m.MainBalance
	}
	return 0
}

func (m *UserAccountBalanceResp) GetCommonResp() *CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

// 4. 云钱包收支明细
type CloudWalletRecordListReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Date                 string   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	PageNum              int32    `protobuf:"varint,3,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize             int32    `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	OperationID          string   `protobuf:"bytes,5,opt,name=operationID,proto3" json:"operationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloudWalletRecordListReq) Reset()         { *m = CloudWalletRecordListReq{} }
func (m *CloudWalletRecordListReq) String() string { return proto.CompactTextString(m) }
func (*CloudWalletRecordListReq) ProtoMessage()    {}
func (*CloudWalletRecordListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{5}
}

func (m *CloudWalletRecordListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudWalletRecordListReq.Unmarshal(m, b)
}
func (m *CloudWalletRecordListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudWalletRecordListReq.Marshal(b, m, deterministic)
}
func (m *CloudWalletRecordListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudWalletRecordListReq.Merge(m, src)
}
func (m *CloudWalletRecordListReq) XXX_Size() int {
	return xxx_messageInfo_CloudWalletRecordListReq.Size(m)
}
func (m *CloudWalletRecordListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudWalletRecordListReq.DiscardUnknown(m)
}

var xxx_messageInfo_CloudWalletRecordListReq proto.InternalMessageInfo

func (m *CloudWalletRecordListReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CloudWalletRecordListReq) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *CloudWalletRecordListReq) GetPageNum() int32 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *CloudWalletRecordListReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *CloudWalletRecordListReq) GetOperationID() string {
	if m != nil {
		return m.OperationID
	}
	return ""
}

type CloudWalletRecordListResp struct {
	UserId               string        `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Total                int32         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	RecordList           []*RecordList `protobuf:"bytes,3,rep,name=recordList,proto3" json:"recordList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CloudWalletRecordListResp) Reset()         { *m = CloudWalletRecordListResp{} }
func (m *CloudWalletRecordListResp) String() string { return proto.CompactTextString(m) }
func (*CloudWalletRecordListResp) ProtoMessage()    {}
func (*CloudWalletRecordListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{6}
}

func (m *CloudWalletRecordListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudWalletRecordListResp.Unmarshal(m, b)
}
func (m *CloudWalletRecordListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudWalletRecordListResp.Marshal(b, m, deterministic)
}
func (m *CloudWalletRecordListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudWalletRecordListResp.Merge(m, src)
}
func (m *CloudWalletRecordListResp) XXX_Size() int {
	return xxx_messageInfo_CloudWalletRecordListResp.Size(m)
}
func (m *CloudWalletRecordListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudWalletRecordListResp.DiscardUnknown(m)
}

var xxx_messageInfo_CloudWalletRecordListResp proto.InternalMessageInfo

func (m *CloudWalletRecordListResp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CloudWalletRecordListResp) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *CloudWalletRecordListResp) GetRecordList() []*RecordList {
	if m != nil {
		return m.RecordList
	}
	return nil
}

type RecordList struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	AfterAmount          float32  `protobuf:"fixed32,4,opt,name=afterAmount,proto3" json:"afterAmount,omitempty"`
	CreatedTime          int64    `protobuf:"varint,5,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	Remark               string   `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordList) Reset()         { *m = RecordList{} }
func (m *RecordList) String() string { return proto.CompactTextString(m) }
func (*RecordList) ProtoMessage()    {}
func (*RecordList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{7}
}

func (m *RecordList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordList.Unmarshal(m, b)
}
func (m *RecordList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordList.Marshal(b, m, deterministic)
}
func (m *RecordList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordList.Merge(m, src)
}
func (m *RecordList) XXX_Size() int {
	return xxx_messageInfo_RecordList.Size(m)
}
func (m *RecordList) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordList.DiscardUnknown(m)
}

var xxx_messageInfo_RecordList proto.InternalMessageInfo

func (m *RecordList) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RecordList) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *RecordList) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *RecordList) GetAfterAmount() float32 {
	if m != nil {
		return m.AfterAmount
	}
	return 0
}

func (m *RecordList) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *RecordList) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

// 5.获取用户的银行卡列表
type GetUserBankcardListReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserBankcardListReq) Reset()         { *m = GetUserBankcardListReq{} }
func (m *GetUserBankcardListReq) String() string { return proto.CompactTextString(m) }
func (*GetUserBankcardListReq) ProtoMessage()    {}
func (*GetUserBankcardListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{8}
}

func (m *GetUserBankcardListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserBankcardListReq.Unmarshal(m, b)
}
func (m *GetUserBankcardListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserBankcardListReq.Marshal(b, m, deterministic)
}
func (m *GetUserBankcardListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserBankcardListReq.Merge(m, src)
}
func (m *GetUserBankcardListReq) XXX_Size() int {
	return xxx_messageInfo_GetUserBankcardListReq.Size(m)
}
func (m *GetUserBankcardListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserBankcardListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserBankcardListReq proto.InternalMessageInfo

func (m *GetUserBankcardListReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserBankcardListResp struct {
	UserId               string          `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	BankCardInfo         []*BankCardInfo `protobuf:"bytes,2,rep,name=bankCardInfo,proto3" json:"bankCardInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetUserBankcardListResp) Reset()         { *m = GetUserBankcardListResp{} }
func (m *GetUserBankcardListResp) String() string { return proto.CompactTextString(m) }
func (*GetUserBankcardListResp) ProtoMessage()    {}
func (*GetUserBankcardListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{9}
}

func (m *GetUserBankcardListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserBankcardListResp.Unmarshal(m, b)
}
func (m *GetUserBankcardListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserBankcardListResp.Marshal(b, m, deterministic)
}
func (m *GetUserBankcardListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserBankcardListResp.Merge(m, src)
}
func (m *GetUserBankcardListResp) XXX_Size() int {
	return xxx_messageInfo_GetUserBankcardListResp.Size(m)
}
func (m *GetUserBankcardListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserBankcardListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserBankcardListResp proto.InternalMessageInfo

func (m *GetUserBankcardListResp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetUserBankcardListResp) GetBankCardInfo() []*BankCardInfo {
	if m != nil {
		return m.BankCardInfo
	}
	return nil
}

type BankCardInfo struct {
	BankCardID           int64    `protobuf:"varint,1,opt,name=bankCardID,proto3" json:"bankCardID,omitempty"`
	CardOwner            string   `protobuf:"bytes,2,opt,name=cardOwner,proto3" json:"cardOwner,omitempty"`
	BankCardType         int32    `protobuf:"varint,3,opt,name=bankCardType,proto3" json:"bankCardType,omitempty"`
	BankCardNumber       string   `protobuf:"bytes,4,opt,name=bankCardNumber,proto3" json:"bankCardNumber,omitempty"`
	CreatedTime          string   `protobuf:"bytes,5,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BankCardInfo) Reset()         { *m = BankCardInfo{} }
func (m *BankCardInfo) String() string { return proto.CompactTextString(m) }
func (*BankCardInfo) ProtoMessage()    {}
func (*BankCardInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{10}
}

func (m *BankCardInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankCardInfo.Unmarshal(m, b)
}
func (m *BankCardInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankCardInfo.Marshal(b, m, deterministic)
}
func (m *BankCardInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankCardInfo.Merge(m, src)
}
func (m *BankCardInfo) XXX_Size() int {
	return xxx_messageInfo_BankCardInfo.Size(m)
}
func (m *BankCardInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BankCardInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BankCardInfo proto.InternalMessageInfo

func (m *BankCardInfo) GetBankCardID() int64 {
	if m != nil {
		return m.BankCardID
	}
	return 0
}

func (m *BankCardInfo) GetCardOwner() string {
	if m != nil {
		return m.CardOwner
	}
	return ""
}

func (m *BankCardInfo) GetBankCardType() int32 {
	if m != nil {
		return m.BankCardType
	}
	return 0
}

func (m *BankCardInfo) GetBankCardNumber() string {
	if m != nil {
		return m.BankCardNumber
	}
	return ""
}

func (m *BankCardInfo) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

// 6.添加用户银行卡
type AddUserBankcardReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CardOwner            string   `protobuf:"bytes,2,opt,name=cardOwner,proto3" json:"cardOwner,omitempty"`
	BankCardType         int32    `protobuf:"varint,3,opt,name=bankCardType,proto3" json:"bankCardType,omitempty"`
	BankCardNumber       string   `protobuf:"bytes,4,opt,name=bankCardNumber,proto3" json:"bankCardNumber,omitempty"`
	Mobile               string   `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserBankcardReq) Reset()         { *m = AddUserBankcardReq{} }
func (m *AddUserBankcardReq) String() string { return proto.CompactTextString(m) }
func (*AddUserBankcardReq) ProtoMessage()    {}
func (*AddUserBankcardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{11}
}

func (m *AddUserBankcardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserBankcardReq.Unmarshal(m, b)
}
func (m *AddUserBankcardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserBankcardReq.Marshal(b, m, deterministic)
}
func (m *AddUserBankcardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserBankcardReq.Merge(m, src)
}
func (m *AddUserBankcardReq) XXX_Size() int {
	return xxx_messageInfo_AddUserBankcardReq.Size(m)
}
func (m *AddUserBankcardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserBankcardReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserBankcardReq proto.InternalMessageInfo

func (m *AddUserBankcardReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddUserBankcardReq) GetCardOwner() string {
	if m != nil {
		return m.CardOwner
	}
	return ""
}

func (m *AddUserBankcardReq) GetBankCardType() int32 {
	if m != nil {
		return m.BankCardType
	}
	return 0
}

func (m *AddUserBankcardReq) GetBankCardNumber() string {
	if m != nil {
		return m.BankCardNumber
	}
	return ""
}

func (m *AddUserBankcardReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type AddUserBankcardResp struct {
	CommonResp           *CommonResp `protobuf:"bytes,1,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddUserBankcardResp) Reset()         { *m = AddUserBankcardResp{} }
func (m *AddUserBankcardResp) String() string { return proto.CompactTextString(m) }
func (*AddUserBankcardResp) ProtoMessage()    {}
func (*AddUserBankcardResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{12}
}

func (m *AddUserBankcardResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserBankcardResp.Unmarshal(m, b)
}
func (m *AddUserBankcardResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserBankcardResp.Marshal(b, m, deterministic)
}
func (m *AddUserBankcardResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserBankcardResp.Merge(m, src)
}
func (m *AddUserBankcardResp) XXX_Size() int {
	return xxx_messageInfo_AddUserBankcardResp.Size(m)
}
func (m *AddUserBankcardResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserBankcardResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserBankcardResp proto.InternalMessageInfo

func (m *AddUserBankcardResp) GetCommonResp() *CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

// 7.设置用户支付密码
type SetPaymentSecretReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PaymentSecret        int64    `protobuf:"varint,2,opt,name=paymentSecret,proto3" json:"paymentSecret,omitempty"`
	OperationID          string   `protobuf:"bytes,3,opt,name=operationID,proto3" json:"operationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPaymentSecretReq) Reset()         { *m = SetPaymentSecretReq{} }
func (m *SetPaymentSecretReq) String() string { return proto.CompactTextString(m) }
func (*SetPaymentSecretReq) ProtoMessage()    {}
func (*SetPaymentSecretReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{13}
}

func (m *SetPaymentSecretReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPaymentSecretReq.Unmarshal(m, b)
}
func (m *SetPaymentSecretReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPaymentSecretReq.Marshal(b, m, deterministic)
}
func (m *SetPaymentSecretReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPaymentSecretReq.Merge(m, src)
}
func (m *SetPaymentSecretReq) XXX_Size() int {
	return xxx_messageInfo_SetPaymentSecretReq.Size(m)
}
func (m *SetPaymentSecretReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPaymentSecretReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetPaymentSecretReq proto.InternalMessageInfo

func (m *SetPaymentSecretReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SetPaymentSecretReq) GetPaymentSecret() int64 {
	if m != nil {
		return m.PaymentSecret
	}
	return 0
}

func (m *SetPaymentSecretReq) GetOperationID() string {
	if m != nil {
		return m.OperationID
	}
	return ""
}

type SetPaymentSecretResp struct {
	CommonResp           *CommonResp `protobuf:"bytes,1,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SetPaymentSecretResp) Reset()         { *m = SetPaymentSecretResp{} }
func (m *SetPaymentSecretResp) String() string { return proto.CompactTextString(m) }
func (*SetPaymentSecretResp) ProtoMessage()    {}
func (*SetPaymentSecretResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{14}
}

func (m *SetPaymentSecretResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPaymentSecretResp.Unmarshal(m, b)
}
func (m *SetPaymentSecretResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPaymentSecretResp.Marshal(b, m, deterministic)
}
func (m *SetPaymentSecretResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPaymentSecretResp.Merge(m, src)
}
func (m *SetPaymentSecretResp) XXX_Size() int {
	return xxx_messageInfo_SetPaymentSecretResp.Size(m)
}
func (m *SetPaymentSecretResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPaymentSecretResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetPaymentSecretResp proto.InternalMessageInfo

func (m *SetPaymentSecretResp) GetCommonResp() *CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

// 8.用户密码认证  部分操作需要用户密码认证
type UserPaymentSecretAuthReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PaymentSecret        string   `protobuf:"bytes,2,opt,name=paymentSecret,proto3" json:"paymentSecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserPaymentSecretAuthReq) Reset()         { *m = UserPaymentSecretAuthReq{} }
func (m *UserPaymentSecretAuthReq) String() string { return proto.CompactTextString(m) }
func (*UserPaymentSecretAuthReq) ProtoMessage()    {}
func (*UserPaymentSecretAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{15}
}

func (m *UserPaymentSecretAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPaymentSecretAuthReq.Unmarshal(m, b)
}
func (m *UserPaymentSecretAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPaymentSecretAuthReq.Marshal(b, m, deterministic)
}
func (m *UserPaymentSecretAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPaymentSecretAuthReq.Merge(m, src)
}
func (m *UserPaymentSecretAuthReq) XXX_Size() int {
	return xxx_messageInfo_UserPaymentSecretAuthReq.Size(m)
}
func (m *UserPaymentSecretAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPaymentSecretAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserPaymentSecretAuthReq proto.InternalMessageInfo

func (m *UserPaymentSecretAuthReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserPaymentSecretAuthReq) GetPaymentSecret() string {
	if m != nil {
		return m.PaymentSecret
	}
	return ""
}

type UserPaymentSecretAuthResp struct {
	CommonResp           *CommonResp `protobuf:"bytes,1,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserPaymentSecretAuthResp) Reset()         { *m = UserPaymentSecretAuthResp{} }
func (m *UserPaymentSecretAuthResp) String() string { return proto.CompactTextString(m) }
func (*UserPaymentSecretAuthResp) ProtoMessage()    {}
func (*UserPaymentSecretAuthResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{16}
}

func (m *UserPaymentSecretAuthResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserPaymentSecretAuthResp.Unmarshal(m, b)
}
func (m *UserPaymentSecretAuthResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserPaymentSecretAuthResp.Marshal(b, m, deterministic)
}
func (m *UserPaymentSecretAuthResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserPaymentSecretAuthResp.Merge(m, src)
}
func (m *UserPaymentSecretAuthResp) XXX_Size() int {
	return xxx_messageInfo_UserPaymentSecretAuthResp.Size(m)
}
func (m *UserPaymentSecretAuthResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserPaymentSecretAuthResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserPaymentSecretAuthResp proto.InternalMessageInfo

func (m *UserPaymentSecretAuthResp) GetCommonResp() *CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

// 8. 银行卡充值到用户钱包
type ChargeAccountReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	BankCardID           string   `protobuf:"bytes,2,opt,name=bankCardID,proto3" json:"bankCardID,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChargeAccountReq) Reset()         { *m = ChargeAccountReq{} }
func (m *ChargeAccountReq) String() string { return proto.CompactTextString(m) }
func (*ChargeAccountReq) ProtoMessage()    {}
func (*ChargeAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{17}
}

func (m *ChargeAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeAccountReq.Unmarshal(m, b)
}
func (m *ChargeAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeAccountReq.Marshal(b, m, deterministic)
}
func (m *ChargeAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeAccountReq.Merge(m, src)
}
func (m *ChargeAccountReq) XXX_Size() int {
	return xxx_messageInfo_ChargeAccountReq.Size(m)
}
func (m *ChargeAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeAccountReq proto.InternalMessageInfo

func (m *ChargeAccountReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ChargeAccountReq) GetBankCardID() string {
	if m != nil {
		return m.BankCardID
	}
	return ""
}

func (m *ChargeAccountReq) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ChargeAccountResp struct {
	Amount               int64       `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	CommonResp           *CommonResp `protobuf:"bytes,2,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChargeAccountResp) Reset()         { *m = ChargeAccountResp{} }
func (m *ChargeAccountResp) String() string { return proto.CompactTextString(m) }
func (*ChargeAccountResp) ProtoMessage()    {}
func (*ChargeAccountResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{18}
}

func (m *ChargeAccountResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeAccountResp.Unmarshal(m, b)
}
func (m *ChargeAccountResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeAccountResp.Marshal(b, m, deterministic)
}
func (m *ChargeAccountResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeAccountResp.Merge(m, src)
}
func (m *ChargeAccountResp) XXX_Size() int {
	return xxx_messageInfo_ChargeAccountResp.Size(m)
}
func (m *ChargeAccountResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeAccountResp.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeAccountResp proto.InternalMessageInfo

func (m *ChargeAccountResp) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ChargeAccountResp) GetCommonResp() *CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

// 9. 用户钱包提现到银行卡
type DrawAccountReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	BankCardID           string   `protobuf:"bytes,2,opt,name=bankCardID,proto3" json:"bankCardID,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawAccountReq) Reset()         { *m = DrawAccountReq{} }
func (m *DrawAccountReq) String() string { return proto.CompactTextString(m) }
func (*DrawAccountReq) ProtoMessage()    {}
func (*DrawAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{19}
}

func (m *DrawAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawAccountReq.Unmarshal(m, b)
}
func (m *DrawAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawAccountReq.Marshal(b, m, deterministic)
}
func (m *DrawAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawAccountReq.Merge(m, src)
}
func (m *DrawAccountReq) XXX_Size() int {
	return xxx_messageInfo_DrawAccountReq.Size(m)
}
func (m *DrawAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_DrawAccountReq proto.InternalMessageInfo

func (m *DrawAccountReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DrawAccountReq) GetBankCardID() string {
	if m != nil {
		return m.BankCardID
	}
	return ""
}

func (m *DrawAccountReq) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type DrawAccountResp struct {
	Amount               int64       `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	CommonResp           *CommonResp `protobuf:"bytes,2,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DrawAccountResp) Reset()         { *m = DrawAccountResp{} }
func (m *DrawAccountResp) String() string { return proto.CompactTextString(m) }
func (*DrawAccountResp) ProtoMessage()    {}
func (*DrawAccountResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{20}
}

func (m *DrawAccountResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawAccountResp.Unmarshal(m, b)
}
func (m *DrawAccountResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawAccountResp.Marshal(b, m, deterministic)
}
func (m *DrawAccountResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawAccountResp.Merge(m, src)
}
func (m *DrawAccountResp) XXX_Size() int {
	return xxx_messageInfo_DrawAccountResp.Size(m)
}
func (m *DrawAccountResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawAccountResp.DiscardUnknown(m)
}

var xxx_messageInfo_DrawAccountResp proto.InternalMessageInfo

func (m *DrawAccountResp) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *DrawAccountResp) GetCommonResp() *CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

// 10. 发红包
type SendRedPacketReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PacketType           int32    `protobuf:"varint,2,opt,name=PacketType,proto3" json:"PacketType,omitempty"`
	IsLucky              int32    `protobuf:"varint,3,opt,name=IsLucky,proto3" json:"IsLucky,omitempty"`
	IsExclusive          int32    `protobuf:"varint,4,opt,name=IsExclusive,proto3" json:"IsExclusive,omitempty"`
	PacketTitle          string   `protobuf:"bytes,5,opt,name=PacketTitle,proto3" json:"PacketTitle,omitempty"`
	Amount               float32  `protobuf:"fixed32,6,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Number               int32    `protobuf:"varint,7,opt,name=Number,proto3" json:"Number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRedPacketReq) Reset()         { *m = SendRedPacketReq{} }
func (m *SendRedPacketReq) String() string { return proto.CompactTextString(m) }
func (*SendRedPacketReq) ProtoMessage()    {}
func (*SendRedPacketReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{21}
}

func (m *SendRedPacketReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRedPacketReq.Unmarshal(m, b)
}
func (m *SendRedPacketReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRedPacketReq.Marshal(b, m, deterministic)
}
func (m *SendRedPacketReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRedPacketReq.Merge(m, src)
}
func (m *SendRedPacketReq) XXX_Size() int {
	return xxx_messageInfo_SendRedPacketReq.Size(m)
}
func (m *SendRedPacketReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRedPacketReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendRedPacketReq proto.InternalMessageInfo

func (m *SendRedPacketReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SendRedPacketReq) GetPacketType() int32 {
	if m != nil {
		return m.PacketType
	}
	return 0
}

func (m *SendRedPacketReq) GetIsLucky() int32 {
	if m != nil {
		return m.IsLucky
	}
	return 0
}

func (m *SendRedPacketReq) GetIsExclusive() int32 {
	if m != nil {
		return m.IsExclusive
	}
	return 0
}

func (m *SendRedPacketReq) GetPacketTitle() string {
	if m != nil {
		return m.PacketTitle
	}
	return ""
}

func (m *SendRedPacketReq) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *SendRedPacketReq) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type SendRedPacketResp struct {
	RedPacketID          int32       `protobuf:"varint,1,opt,name=redPacketID,proto3" json:"redPacketID,omitempty"`
	CommonResp           *CommonResp `protobuf:"bytes,2,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SendRedPacketResp) Reset()         { *m = SendRedPacketResp{} }
func (m *SendRedPacketResp) String() string { return proto.CompactTextString(m) }
func (*SendRedPacketResp) ProtoMessage()    {}
func (*SendRedPacketResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{22}
}

func (m *SendRedPacketResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRedPacketResp.Unmarshal(m, b)
}
func (m *SendRedPacketResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRedPacketResp.Marshal(b, m, deterministic)
}
func (m *SendRedPacketResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRedPacketResp.Merge(m, src)
}
func (m *SendRedPacketResp) XXX_Size() int {
	return xxx_messageInfo_SendRedPacketResp.Size(m)
}
func (m *SendRedPacketResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRedPacketResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendRedPacketResp proto.InternalMessageInfo

func (m *SendRedPacketResp) GetRedPacketID() int32 {
	if m != nil {
		return m.RedPacketID
	}
	return 0
}

func (m *SendRedPacketResp) GetCommonResp() *CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

// 新红包通知结构体
type RedPackageNotify struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RedPacketID          int64    `protobuf:"varint,2,opt,name=RedPacketID,proto3" json:"RedPacketID,omitempty"`
	SendTime             int64    `protobuf:"varint,3,opt,name=SendTime,proto3" json:"SendTime,omitempty"`
	PacketTitle          string   `protobuf:"bytes,4,opt,name=PacketTitle,proto3" json:"PacketTitle,omitempty"`
	PacketType           int32    `protobuf:"varint,5,opt,name=PacketType,proto3" json:"PacketType,omitempty"`
	IsExclusive          int32    `protobuf:"varint,6,opt,name=IsExclusive,proto3" json:"IsExclusive,omitempty"`
	ExclusiveUserID      int64    `protobuf:"varint,7,opt,name=ExclusiveUserID,proto3" json:"ExclusiveUserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedPackageNotify) Reset()         { *m = RedPackageNotify{} }
func (m *RedPackageNotify) String() string { return proto.CompactTextString(m) }
func (*RedPackageNotify) ProtoMessage()    {}
func (*RedPackageNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{23}
}

func (m *RedPackageNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedPackageNotify.Unmarshal(m, b)
}
func (m *RedPackageNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedPackageNotify.Marshal(b, m, deterministic)
}
func (m *RedPackageNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedPackageNotify.Merge(m, src)
}
func (m *RedPackageNotify) XXX_Size() int {
	return xxx_messageInfo_RedPackageNotify.Size(m)
}
func (m *RedPackageNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_RedPackageNotify.DiscardUnknown(m)
}

var xxx_messageInfo_RedPackageNotify proto.InternalMessageInfo

func (m *RedPackageNotify) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RedPackageNotify) GetRedPacketID() int64 {
	if m != nil {
		return m.RedPacketID
	}
	return 0
}

func (m *RedPackageNotify) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *RedPackageNotify) GetPacketTitle() string {
	if m != nil {
		return m.PacketTitle
	}
	return ""
}

func (m *RedPackageNotify) GetPacketType() int32 {
	if m != nil {
		return m.PacketType
	}
	return 0
}

func (m *RedPackageNotify) GetIsExclusive() int32 {
	if m != nil {
		return m.IsExclusive
	}
	return 0
}

func (m *RedPackageNotify) GetExclusiveUserID() int64 {
	if m != nil {
		return m.ExclusiveUserID
	}
	return 0
}

// 红包被领取通知发送红包者 的结构体
type RedPackageClickedNotify struct {
	PacketID             int64    `protobuf:"varint,1,opt,name=PacketID,proto3" json:"PacketID,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedPackageClickedNotify) Reset()         { *m = RedPackageClickedNotify{} }
func (m *RedPackageClickedNotify) String() string { return proto.CompactTextString(m) }
func (*RedPackageClickedNotify) ProtoMessage()    {}
func (*RedPackageClickedNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{24}
}

func (m *RedPackageClickedNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedPackageClickedNotify.Unmarshal(m, b)
}
func (m *RedPackageClickedNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedPackageClickedNotify.Marshal(b, m, deterministic)
}
func (m *RedPackageClickedNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedPackageClickedNotify.Merge(m, src)
}
func (m *RedPackageClickedNotify) XXX_Size() int {
	return xxx_messageInfo_RedPackageClickedNotify.Size(m)
}
func (m *RedPackageClickedNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_RedPackageClickedNotify.DiscardUnknown(m)
}

var xxx_messageInfo_RedPackageClickedNotify proto.InternalMessageInfo

func (m *RedPackageClickedNotify) GetPacketID() int64 {
	if m != nil {
		return m.PacketID
	}
	return 0
}

func (m *RedPackageClickedNotify) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RedPackageClickedNotify) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

// 11. 抢红包
type ClickRedPacketReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RedPacketID          int32    `protobuf:"varint,2,opt,name=redPacketID,proto3" json:"redPacketID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClickRedPacketReq) Reset()         { *m = ClickRedPacketReq{} }
func (m *ClickRedPacketReq) String() string { return proto.CompactTextString(m) }
func (*ClickRedPacketReq) ProtoMessage()    {}
func (*ClickRedPacketReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{25}
}

func (m *ClickRedPacketReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClickRedPacketReq.Unmarshal(m, b)
}
func (m *ClickRedPacketReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClickRedPacketReq.Marshal(b, m, deterministic)
}
func (m *ClickRedPacketReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClickRedPacketReq.Merge(m, src)
}
func (m *ClickRedPacketReq) XXX_Size() int {
	return xxx_messageInfo_ClickRedPacketReq.Size(m)
}
func (m *ClickRedPacketReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ClickRedPacketReq.DiscardUnknown(m)
}

var xxx_messageInfo_ClickRedPacketReq proto.InternalMessageInfo

func (m *ClickRedPacketReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ClickRedPacketReq) GetRedPacketID() int32 {
	if m != nil {
		return m.RedPacketID
	}
	return 0
}

type ClickRedPacketResp struct {
	UserId               string      `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RedPacketID          string      `protobuf:"bytes,2,opt,name=redPacketID,proto3" json:"redPacketID,omitempty"`
	Amount               string      `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	IsReceive            int32       `protobuf:"varint,4,opt,name=isReceive,proto3" json:"isReceive,omitempty"`
	CommonResp           *CommonResp `protobuf:"bytes,5,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ClickRedPacketResp) Reset()         { *m = ClickRedPacketResp{} }
func (m *ClickRedPacketResp) String() string { return proto.CompactTextString(m) }
func (*ClickRedPacketResp) ProtoMessage()    {}
func (*ClickRedPacketResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{26}
}

func (m *ClickRedPacketResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClickRedPacketResp.Unmarshal(m, b)
}
func (m *ClickRedPacketResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClickRedPacketResp.Marshal(b, m, deterministic)
}
func (m *ClickRedPacketResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClickRedPacketResp.Merge(m, src)
}
func (m *ClickRedPacketResp) XXX_Size() int {
	return xxx_messageInfo_ClickRedPacketResp.Size(m)
}
func (m *ClickRedPacketResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ClickRedPacketResp.DiscardUnknown(m)
}

var xxx_messageInfo_ClickRedPacketResp proto.InternalMessageInfo

func (m *ClickRedPacketResp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ClickRedPacketResp) GetRedPacketID() string {
	if m != nil {
		return m.RedPacketID
	}
	return ""
}

func (m *ClickRedPacketResp) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *ClickRedPacketResp) GetIsReceive() int32 {
	if m != nil {
		return m.IsReceive
	}
	return 0
}

func (m *ClickRedPacketResp) GetCommonResp() *CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

// 12. 获取红包信息
type GetRedPacketInfoReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RedPacketID          string   `protobuf:"bytes,2,opt,name=redPacketID,proto3" json:"redPacketID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRedPacketInfoReq) Reset()         { *m = GetRedPacketInfoReq{} }
func (m *GetRedPacketInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetRedPacketInfoReq) ProtoMessage()    {}
func (*GetRedPacketInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{27}
}

func (m *GetRedPacketInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRedPacketInfoReq.Unmarshal(m, b)
}
func (m *GetRedPacketInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRedPacketInfoReq.Marshal(b, m, deterministic)
}
func (m *GetRedPacketInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRedPacketInfoReq.Merge(m, src)
}
func (m *GetRedPacketInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetRedPacketInfoReq.Size(m)
}
func (m *GetRedPacketInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRedPacketInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRedPacketInfoReq proto.InternalMessageInfo

func (m *GetRedPacketInfoReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetRedPacketInfoReq) GetRedPacketID() string {
	if m != nil {
		return m.RedPacketID
	}
	return ""
}

type GetRedPacketInfoResp struct {
	UserId               string      `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PacketType           int32       `protobuf:"varint,2,opt,name=packetType,proto3" json:"packetType,omitempty"`
	IsLucky              int32       `protobuf:"varint,3,opt,name=is_lucky,json=isLucky,proto3" json:"is_lucky,omitempty"`
	IsExclusive          int32       `protobuf:"varint,4,opt,name=is_exclusive,json=isExclusive,proto3" json:"is_exclusive,omitempty"`
	ExclusiveUserID      int32       `protobuf:"varint,5,opt,name=exclusiveUserID,proto3" json:"exclusiveUserID,omitempty"`
	PacketTitle          string      `protobuf:"bytes,6,opt,name=packet_title,json=packetTitle,proto3" json:"packet_title,omitempty"`
	Amount               float32     `protobuf:"fixed32,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Number               int32       `protobuf:"varint,8,opt,name=number,proto3" json:"number,omitempty"`
	ExpireTime           string      `protobuf:"bytes,9,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	IsReceiveCompleted   float32     `protobuf:"fixed32,10,opt,name=isReceiveCompleted,proto3" json:"isReceiveCompleted,omitempty"`
	CommonResp           *CommonResp `protobuf:"bytes,11,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetRedPacketInfoResp) Reset()         { *m = GetRedPacketInfoResp{} }
func (m *GetRedPacketInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetRedPacketInfoResp) ProtoMessage()    {}
func (*GetRedPacketInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{28}
}

func (m *GetRedPacketInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRedPacketInfoResp.Unmarshal(m, b)
}
func (m *GetRedPacketInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRedPacketInfoResp.Marshal(b, m, deterministic)
}
func (m *GetRedPacketInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRedPacketInfoResp.Merge(m, src)
}
func (m *GetRedPacketInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetRedPacketInfoResp.Size(m)
}
func (m *GetRedPacketInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRedPacketInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetRedPacketInfoResp proto.InternalMessageInfo

func (m *GetRedPacketInfoResp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetRedPacketInfoResp) GetPacketType() int32 {
	if m != nil {
		return m.PacketType
	}
	return 0
}

func (m *GetRedPacketInfoResp) GetIsLucky() int32 {
	if m != nil {
		return m.IsLucky
	}
	return 0
}

func (m *GetRedPacketInfoResp) GetIsExclusive() int32 {
	if m != nil {
		return m.IsExclusive
	}
	return 0
}

func (m *GetRedPacketInfoResp) GetExclusiveUserID() int32 {
	if m != nil {
		return m.ExclusiveUserID
	}
	return 0
}

func (m *GetRedPacketInfoResp) GetPacketTitle() string {
	if m != nil {
		return m.PacketTitle
	}
	return ""
}

func (m *GetRedPacketInfoResp) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *GetRedPacketInfoResp) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *GetRedPacketInfoResp) GetExpireTime() string {
	if m != nil {
		return m.ExpireTime
	}
	return ""
}

func (m *GetRedPacketInfoResp) GetIsReceiveCompleted() float32 {
	if m != nil {
		return m.IsReceiveCompleted
	}
	return 0
}

func (m *GetRedPacketInfoResp) GetCommonResp() *CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

// 13. 红包领取明细
type RedPacketClickDetailReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RedPacketID          string   `protobuf:"bytes,2,opt,name=redPacketID,proto3" json:"redPacketID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedPacketClickDetailReq) Reset()         { *m = RedPacketClickDetailReq{} }
func (m *RedPacketClickDetailReq) String() string { return proto.CompactTextString(m) }
func (*RedPacketClickDetailReq) ProtoMessage()    {}
func (*RedPacketClickDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{29}
}

func (m *RedPacketClickDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedPacketClickDetailReq.Unmarshal(m, b)
}
func (m *RedPacketClickDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedPacketClickDetailReq.Marshal(b, m, deterministic)
}
func (m *RedPacketClickDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedPacketClickDetailReq.Merge(m, src)
}
func (m *RedPacketClickDetailReq) XXX_Size() int {
	return xxx_messageInfo_RedPacketClickDetailReq.Size(m)
}
func (m *RedPacketClickDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RedPacketClickDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_RedPacketClickDetailReq proto.InternalMessageInfo

func (m *RedPacketClickDetailReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RedPacketClickDetailReq) GetRedPacketID() string {
	if m != nil {
		return m.RedPacketID
	}
	return ""
}

type RedPacketClickDetail struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avater               string   `protobuf:"bytes,3,opt,name=avater,proto3" json:"avater,omitempty"`
	RedPacketID          uint32   `protobuf:"varint,4,opt,name=redPacketID,proto3" json:"redPacketID,omitempty"`
	Amount               float32  `protobuf:"fixed32,5,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedPacketClickDetail) Reset()         { *m = RedPacketClickDetail{} }
func (m *RedPacketClickDetail) String() string { return proto.CompactTextString(m) }
func (*RedPacketClickDetail) ProtoMessage()    {}
func (*RedPacketClickDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{30}
}

func (m *RedPacketClickDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedPacketClickDetail.Unmarshal(m, b)
}
func (m *RedPacketClickDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedPacketClickDetail.Marshal(b, m, deterministic)
}
func (m *RedPacketClickDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedPacketClickDetail.Merge(m, src)
}
func (m *RedPacketClickDetail) XXX_Size() int {
	return xxx_messageInfo_RedPacketClickDetail.Size(m)
}
func (m *RedPacketClickDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_RedPacketClickDetail.DiscardUnknown(m)
}

var xxx_messageInfo_RedPacketClickDetail proto.InternalMessageInfo

func (m *RedPacketClickDetail) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RedPacketClickDetail) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RedPacketClickDetail) GetAvater() string {
	if m != nil {
		return m.Avater
	}
	return ""
}

func (m *RedPacketClickDetail) GetRedPacketID() uint32 {
	if m != nil {
		return m.RedPacketID
	}
	return 0
}

func (m *RedPacketClickDetail) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type RedPacketClickDetailResp struct {
	RedPacketClickDetail []*RedPacketClickDetail `protobuf:"bytes,1,rep,name=redPacketClickDetail,proto3" json:"redPacketClickDetail,omitempty"`
	CommonResp           *CommonResp             `protobuf:"bytes,2,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RedPacketClickDetailResp) Reset()         { *m = RedPacketClickDetailResp{} }
func (m *RedPacketClickDetailResp) String() string { return proto.CompactTextString(m) }
func (*RedPacketClickDetailResp) ProtoMessage()    {}
func (*RedPacketClickDetailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{31}
}

func (m *RedPacketClickDetailResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedPacketClickDetailResp.Unmarshal(m, b)
}
func (m *RedPacketClickDetailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedPacketClickDetailResp.Marshal(b, m, deterministic)
}
func (m *RedPacketClickDetailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedPacketClickDetailResp.Merge(m, src)
}
func (m *RedPacketClickDetailResp) XXX_Size() int {
	return xxx_messageInfo_RedPacketClickDetailResp.Size(m)
}
func (m *RedPacketClickDetailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RedPacketClickDetailResp.DiscardUnknown(m)
}

var xxx_messageInfo_RedPacketClickDetailResp proto.InternalMessageInfo

func (m *RedPacketClickDetailResp) GetRedPacketClickDetail() []*RedPacketClickDetail {
	if m != nil {
		return m.RedPacketClickDetail
	}
	return nil
}

func (m *RedPacketClickDetailResp) GetCommonResp() *CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

type ListRedPacketRecordReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Date                 string   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRedPacketRecordReq) Reset()         { *m = ListRedPacketRecordReq{} }
func (m *ListRedPacketRecordReq) String() string { return proto.CompactTextString(m) }
func (*ListRedPacketRecordReq) ProtoMessage()    {}
func (*ListRedPacketRecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{32}
}

func (m *ListRedPacketRecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRedPacketRecordReq.Unmarshal(m, b)
}
func (m *ListRedPacketRecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRedPacketRecordReq.Marshal(b, m, deterministic)
}
func (m *ListRedPacketRecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRedPacketRecordReq.Merge(m, src)
}
func (m *ListRedPacketRecordReq) XXX_Size() int {
	return xxx_messageInfo_ListRedPacketRecordReq.Size(m)
}
func (m *ListRedPacketRecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRedPacketRecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListRedPacketRecordReq proto.InternalMessageInfo

func (m *ListRedPacketRecordReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListRedPacketRecordReq) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type ListRedPacketRecordResp struct {
	UserId               string      `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Nickname             string      `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avater               string      `protobuf:"bytes,3,opt,name=avater,proto3" json:"avater,omitempty"`
	RedPacketID          uint32      `protobuf:"varint,4,opt,name=redPacketID,proto3" json:"redPacketID,omitempty"`
	RedPacketTitle       string      `protobuf:"bytes,5,opt,name=redPacketTitle,proto3" json:"redPacketTitle,omitempty"`
	Amount               float32     `protobuf:"fixed32,6,opt,name=amount,proto3" json:"amount,omitempty"`
	CommonResp           *CommonResp `protobuf:"bytes,7,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListRedPacketRecordResp) Reset()         { *m = ListRedPacketRecordResp{} }
func (m *ListRedPacketRecordResp) String() string { return proto.CompactTextString(m) }
func (*ListRedPacketRecordResp) ProtoMessage()    {}
func (*ListRedPacketRecordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{33}
}

func (m *ListRedPacketRecordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRedPacketRecordResp.Unmarshal(m, b)
}
func (m *ListRedPacketRecordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRedPacketRecordResp.Marshal(b, m, deterministic)
}
func (m *ListRedPacketRecordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRedPacketRecordResp.Merge(m, src)
}
func (m *ListRedPacketRecordResp) XXX_Size() int {
	return xxx_messageInfo_ListRedPacketRecordResp.Size(m)
}
func (m *ListRedPacketRecordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRedPacketRecordResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListRedPacketRecordResp proto.InternalMessageInfo

func (m *ListRedPacketRecordResp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListRedPacketRecordResp) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *ListRedPacketRecordResp) GetAvater() string {
	if m != nil {
		return m.Avater
	}
	return ""
}

func (m *ListRedPacketRecordResp) GetRedPacketID() uint32 {
	if m != nil {
		return m.RedPacketID
	}
	return 0
}

func (m *ListRedPacketRecordResp) GetRedPacketTitle() string {
	if m != nil {
		return m.RedPacketTitle
	}
	return ""
}

func (m *ListRedPacketRecordResp) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ListRedPacketRecordResp) GetCommonResp() *CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

// 15. 确认发送红包的code
type ConfirmSendRedPacketCodeReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RedPacketID          string   `protobuf:"bytes,2,opt,name=redPacketID,proto3" json:"redPacketID,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmSendRedPacketCodeReq) Reset()         { *m = ConfirmSendRedPacketCodeReq{} }
func (m *ConfirmSendRedPacketCodeReq) String() string { return proto.CompactTextString(m) }
func (*ConfirmSendRedPacketCodeReq) ProtoMessage()    {}
func (*ConfirmSendRedPacketCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{34}
}

func (m *ConfirmSendRedPacketCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmSendRedPacketCodeReq.Unmarshal(m, b)
}
func (m *ConfirmSendRedPacketCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmSendRedPacketCodeReq.Marshal(b, m, deterministic)
}
func (m *ConfirmSendRedPacketCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmSendRedPacketCodeReq.Merge(m, src)
}
func (m *ConfirmSendRedPacketCodeReq) XXX_Size() int {
	return xxx_messageInfo_ConfirmSendRedPacketCodeReq.Size(m)
}
func (m *ConfirmSendRedPacketCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmSendRedPacketCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmSendRedPacketCodeReq proto.InternalMessageInfo

func (m *ConfirmSendRedPacketCodeReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ConfirmSendRedPacketCodeReq) GetRedPacketID() string {
	if m != nil {
		return m.RedPacketID
	}
	return ""
}

func (m *ConfirmSendRedPacketCodeReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ConfirmSendRedPacketCodeResp struct {
	CommonResp           *CommonResp `protobuf:"bytes,1,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConfirmSendRedPacketCodeResp) Reset()         { *m = ConfirmSendRedPacketCodeResp{} }
func (m *ConfirmSendRedPacketCodeResp) String() string { return proto.CompactTextString(m) }
func (*ConfirmSendRedPacketCodeResp) ProtoMessage()    {}
func (*ConfirmSendRedPacketCodeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{35}
}

func (m *ConfirmSendRedPacketCodeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmSendRedPacketCodeResp.Unmarshal(m, b)
}
func (m *ConfirmSendRedPacketCodeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmSendRedPacketCodeResp.Marshal(b, m, deterministic)
}
func (m *ConfirmSendRedPacketCodeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmSendRedPacketCodeResp.Merge(m, src)
}
func (m *ConfirmSendRedPacketCodeResp) XXX_Size() int {
	return xxx_messageInfo_ConfirmSendRedPacketCodeResp.Size(m)
}
func (m *ConfirmSendRedPacketCodeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmSendRedPacketCodeResp.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmSendRedPacketCodeResp proto.InternalMessageInfo

func (m *ConfirmSendRedPacketCodeResp) GetCommonResp() *CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

// ==============================================回调 ===================
// 16. 用户从银行卡充值到红包、充值到主账户都需要进行回调
type ChargeNotifyReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	BankCardID           string   `protobuf:"bytes,2,opt,name=bankCardID,proto3" json:"bankCardID,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChargeNotifyReq) Reset()         { *m = ChargeNotifyReq{} }
func (m *ChargeNotifyReq) String() string { return proto.CompactTextString(m) }
func (*ChargeNotifyReq) ProtoMessage()    {}
func (*ChargeNotifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{36}
}

func (m *ChargeNotifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeNotifyReq.Unmarshal(m, b)
}
func (m *ChargeNotifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeNotifyReq.Marshal(b, m, deterministic)
}
func (m *ChargeNotifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeNotifyReq.Merge(m, src)
}
func (m *ChargeNotifyReq) XXX_Size() int {
	return xxx_messageInfo_ChargeNotifyReq.Size(m)
}
func (m *ChargeNotifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeNotifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeNotifyReq proto.InternalMessageInfo

func (m *ChargeNotifyReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ChargeNotifyReq) GetBankCardID() string {
	if m != nil {
		return m.BankCardID
	}
	return ""
}

func (m *ChargeNotifyReq) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type ChargeNotifyResp struct {
	CommonResp           *CommonResp `protobuf:"bytes,1,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChargeNotifyResp) Reset()         { *m = ChargeNotifyResp{} }
func (m *ChargeNotifyResp) String() string { return proto.CompactTextString(m) }
func (*ChargeNotifyResp) ProtoMessage()    {}
func (*ChargeNotifyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{37}
}

func (m *ChargeNotifyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChargeNotifyResp.Unmarshal(m, b)
}
func (m *ChargeNotifyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChargeNotifyResp.Marshal(b, m, deterministic)
}
func (m *ChargeNotifyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChargeNotifyResp.Merge(m, src)
}
func (m *ChargeNotifyResp) XXX_Size() int {
	return xxx_messageInfo_ChargeNotifyResp.Size(m)
}
func (m *ChargeNotifyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChargeNotifyResp.DiscardUnknown(m)
}

var xxx_messageInfo_ChargeNotifyResp proto.InternalMessageInfo

func (m *ChargeNotifyResp) GetCommonResp() *CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

// 17. 提现的回调接口： 提供给第三方
type DrawNotifyReq struct {
	OrderNo              string   `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	ThirdOrderNo         string   `protobuf:"bytes,2,opt,name=third_order_no,json=thirdOrderNo,proto3" json:"third_order_no,omitempty"`
	BankCardNumber       string   `protobuf:"bytes,3,opt,name=bank_card_number,json=bankCardNumber,proto3" json:"bank_card_number,omitempty"`
	WithdrawalAmount     float32  `protobuf:"fixed32,4,opt,name=withdrawal_amount,json=withdrawalAmount,proto3" json:"withdrawal_amount,omitempty"`
	CardOwner            string   `protobuf:"bytes,5,opt,name=card_owner,json=cardOwner,proto3" json:"card_owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawNotifyReq) Reset()         { *m = DrawNotifyReq{} }
func (m *DrawNotifyReq) String() string { return proto.CompactTextString(m) }
func (*DrawNotifyReq) ProtoMessage()    {}
func (*DrawNotifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{38}
}

func (m *DrawNotifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawNotifyReq.Unmarshal(m, b)
}
func (m *DrawNotifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawNotifyReq.Marshal(b, m, deterministic)
}
func (m *DrawNotifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawNotifyReq.Merge(m, src)
}
func (m *DrawNotifyReq) XXX_Size() int {
	return xxx_messageInfo_DrawNotifyReq.Size(m)
}
func (m *DrawNotifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawNotifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_DrawNotifyReq proto.InternalMessageInfo

func (m *DrawNotifyReq) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *DrawNotifyReq) GetThirdOrderNo() string {
	if m != nil {
		return m.ThirdOrderNo
	}
	return ""
}

func (m *DrawNotifyReq) GetBankCardNumber() string {
	if m != nil {
		return m.BankCardNumber
	}
	return ""
}

func (m *DrawNotifyReq) GetWithdrawalAmount() float32 {
	if m != nil {
		return m.WithdrawalAmount
	}
	return 0
}

func (m *DrawNotifyReq) GetCardOwner() string {
	if m != nil {
		return m.CardOwner
	}
	return ""
}

type DrawNotifyResp struct {
	CommonResp           *CommonResp `protobuf:"bytes,1,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DrawNotifyResp) Reset()         { *m = DrawNotifyResp{} }
func (m *DrawNotifyResp) String() string { return proto.CompactTextString(m) }
func (*DrawNotifyResp) ProtoMessage()    {}
func (*DrawNotifyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{39}
}

func (m *DrawNotifyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawNotifyResp.Unmarshal(m, b)
}
func (m *DrawNotifyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawNotifyResp.Marshal(b, m, deterministic)
}
func (m *DrawNotifyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawNotifyResp.Merge(m, src)
}
func (m *DrawNotifyResp) XXX_Size() int {
	return xxx_messageInfo_DrawNotifyResp.Size(m)
}
func (m *DrawNotifyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawNotifyResp.DiscardUnknown(m)
}

var xxx_messageInfo_DrawNotifyResp proto.InternalMessageInfo

func (m *DrawNotifyResp) GetCommonResp() *CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

// 身份证实名认证
type IdCardRealNameAuthReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	IdCard               string   `protobuf:"bytes,2,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	RealName             string   `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	OperationID          string   `protobuf:"bytes,4,opt,name=operationID,proto3" json:"operationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdCardRealNameAuthReq) Reset()         { *m = IdCardRealNameAuthReq{} }
func (m *IdCardRealNameAuthReq) String() string { return proto.CompactTextString(m) }
func (*IdCardRealNameAuthReq) ProtoMessage()    {}
func (*IdCardRealNameAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{40}
}

func (m *IdCardRealNameAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdCardRealNameAuthReq.Unmarshal(m, b)
}
func (m *IdCardRealNameAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdCardRealNameAuthReq.Marshal(b, m, deterministic)
}
func (m *IdCardRealNameAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdCardRealNameAuthReq.Merge(m, src)
}
func (m *IdCardRealNameAuthReq) XXX_Size() int {
	return xxx_messageInfo_IdCardRealNameAuthReq.Size(m)
}
func (m *IdCardRealNameAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IdCardRealNameAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_IdCardRealNameAuthReq proto.InternalMessageInfo

func (m *IdCardRealNameAuthReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *IdCardRealNameAuthReq) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func (m *IdCardRealNameAuthReq) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *IdCardRealNameAuthReq) GetOperationID() string {
	if m != nil {
		return m.OperationID
	}
	return ""
}

type IdCardRealNameAuthResp struct {
	Step                 uint32      `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	CommonResp           *CommonResp `protobuf:"bytes,2,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IdCardRealNameAuthResp) Reset()         { *m = IdCardRealNameAuthResp{} }
func (m *IdCardRealNameAuthResp) String() string { return proto.CompactTextString(m) }
func (*IdCardRealNameAuthResp) ProtoMessage()    {}
func (*IdCardRealNameAuthResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{41}
}

func (m *IdCardRealNameAuthResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdCardRealNameAuthResp.Unmarshal(m, b)
}
func (m *IdCardRealNameAuthResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdCardRealNameAuthResp.Marshal(b, m, deterministic)
}
func (m *IdCardRealNameAuthResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdCardRealNameAuthResp.Merge(m, src)
}
func (m *IdCardRealNameAuthResp) XXX_Size() int {
	return xxx_messageInfo_IdCardRealNameAuthResp.Size(m)
}
func (m *IdCardRealNameAuthResp) XXX_DiscardUnknown() {
	xxx_messageInfo_IdCardRealNameAuthResp.DiscardUnknown(m)
}

var xxx_messageInfo_IdCardRealNameAuthResp proto.InternalMessageInfo

func (m *IdCardRealNameAuthResp) GetStep() uint32 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *IdCardRealNameAuthResp) GetCommonResp() *CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

type AuthPaymentSecretReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PaymentSecret        string   `protobuf:"bytes,2,opt,name=payment_secret,json=paymentSecret,proto3" json:"payment_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthPaymentSecretReq) Reset()         { *m = AuthPaymentSecretReq{} }
func (m *AuthPaymentSecretReq) String() string { return proto.CompactTextString(m) }
func (*AuthPaymentSecretReq) ProtoMessage()    {}
func (*AuthPaymentSecretReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{42}
}

func (m *AuthPaymentSecretReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthPaymentSecretReq.Unmarshal(m, b)
}
func (m *AuthPaymentSecretReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthPaymentSecretReq.Marshal(b, m, deterministic)
}
func (m *AuthPaymentSecretReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthPaymentSecretReq.Merge(m, src)
}
func (m *AuthPaymentSecretReq) XXX_Size() int {
	return xxx_messageInfo_AuthPaymentSecretReq.Size(m)
}
func (m *AuthPaymentSecretReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthPaymentSecretReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthPaymentSecretReq proto.InternalMessageInfo

func (m *AuthPaymentSecretReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AuthPaymentSecretReq) GetPaymentSecret() string {
	if m != nil {
		return m.PaymentSecret
	}
	return ""
}

type AuthPaymentSecretResp struct {
	Step                 uint32      `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	CommonResp           *CommonResp `protobuf:"bytes,2,opt,name=commonResp,proto3" json:"commonResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AuthPaymentSecretResp) Reset()         { *m = AuthPaymentSecretResp{} }
func (m *AuthPaymentSecretResp) String() string { return proto.CompactTextString(m) }
func (*AuthPaymentSecretResp) ProtoMessage()    {}
func (*AuthPaymentSecretResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9de16a1887ae03b, []int{43}
}

func (m *AuthPaymentSecretResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthPaymentSecretResp.Unmarshal(m, b)
}
func (m *AuthPaymentSecretResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthPaymentSecretResp.Marshal(b, m, deterministic)
}
func (m *AuthPaymentSecretResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthPaymentSecretResp.Merge(m, src)
}
func (m *AuthPaymentSecretResp) XXX_Size() int {
	return xxx_messageInfo_AuthPaymentSecretResp.Size(m)
}
func (m *AuthPaymentSecretResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthPaymentSecretResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthPaymentSecretResp proto.InternalMessageInfo

func (m *AuthPaymentSecretResp) GetStep() uint32 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *AuthPaymentSecretResp) GetCommonResp() *CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

func init() {
	proto.RegisterType((*CommonResp)(nil), "cloud_wallet.CommonResp")
	proto.RegisterType((*UserNcountAccountReq)(nil), "cloud_wallet.UserNcountAccountReq")
	proto.RegisterType((*UserNcountAccountResp)(nil), "cloud_wallet.UserNcountAccountResp")
	proto.RegisterType((*UserAccountBalanceReq)(nil), "cloud_wallet.UserAccountBalanceReq")
	proto.RegisterType((*UserAccountBalanceResp)(nil), "cloud_wallet.UserAccountBalanceResp")
	proto.RegisterType((*CloudWalletRecordListReq)(nil), "cloud_wallet.CloudWalletRecordListReq")
	proto.RegisterType((*CloudWalletRecordListResp)(nil), "cloud_wallet.CloudWalletRecordListResp")
	proto.RegisterType((*RecordList)(nil), "cloud_wallet.RecordList")
	proto.RegisterType((*GetUserBankcardListReq)(nil), "cloud_wallet.getUserBankcardListReq")
	proto.RegisterType((*GetUserBankcardListResp)(nil), "cloud_wallet.getUserBankcardListResp")
	proto.RegisterType((*BankCardInfo)(nil), "cloud_wallet.BankCardInfo")
	proto.RegisterType((*AddUserBankcardReq)(nil), "cloud_wallet.addUserBankcardReq")
	proto.RegisterType((*AddUserBankcardResp)(nil), "cloud_wallet.addUserBankcardResp")
	proto.RegisterType((*SetPaymentSecretReq)(nil), "cloud_wallet.SetPaymentSecretReq")
	proto.RegisterType((*SetPaymentSecretResp)(nil), "cloud_wallet.SetPaymentSecretResp")
	proto.RegisterType((*UserPaymentSecretAuthReq)(nil), "cloud_wallet.userPaymentSecretAuthReq")
	proto.RegisterType((*UserPaymentSecretAuthResp)(nil), "cloud_wallet.userPaymentSecretAuthResp")
	proto.RegisterType((*ChargeAccountReq)(nil), "cloud_wallet.chargeAccountReq")
	proto.RegisterType((*ChargeAccountResp)(nil), "cloud_wallet.chargeAccountResp")
	proto.RegisterType((*DrawAccountReq)(nil), "cloud_wallet.drawAccountReq")
	proto.RegisterType((*DrawAccountResp)(nil), "cloud_wallet.drawAccountResp")
	proto.RegisterType((*SendRedPacketReq)(nil), "cloud_wallet.sendRedPacketReq")
	proto.RegisterType((*SendRedPacketResp)(nil), "cloud_wallet.sendRedPacketResp")
	proto.RegisterType((*RedPackageNotify)(nil), "cloud_wallet.RedPackageNotify")
	proto.RegisterType((*RedPackageClickedNotify)(nil), "cloud_wallet.RedPackageClickedNotify")
	proto.RegisterType((*ClickRedPacketReq)(nil), "cloud_wallet.clickRedPacketReq")
	proto.RegisterType((*ClickRedPacketResp)(nil), "cloud_wallet.clickRedPacketResp")
	proto.RegisterType((*GetRedPacketInfoReq)(nil), "cloud_wallet.getRedPacketInfoReq")
	proto.RegisterType((*GetRedPacketInfoResp)(nil), "cloud_wallet.getRedPacketInfoResp")
	proto.RegisterType((*RedPacketClickDetailReq)(nil), "cloud_wallet.redPacketClickDetailReq")
	proto.RegisterType((*RedPacketClickDetail)(nil), "cloud_wallet.redPacketClickDetail")
	proto.RegisterType((*RedPacketClickDetailResp)(nil), "cloud_wallet.redPacketClickDetailResp")
	proto.RegisterType((*ListRedPacketRecordReq)(nil), "cloud_wallet.listRedPacketRecordReq")
	proto.RegisterType((*ListRedPacketRecordResp)(nil), "cloud_wallet.listRedPacketRecordResp")
	proto.RegisterType((*ConfirmSendRedPacketCodeReq)(nil), "cloud_wallet.confirmSendRedPacketCodeReq")
	proto.RegisterType((*ConfirmSendRedPacketCodeResp)(nil), "cloud_wallet.confirmSendRedPacketCodeResp")
	proto.RegisterType((*ChargeNotifyReq)(nil), "cloud_wallet.chargeNotifyReq")
	proto.RegisterType((*ChargeNotifyResp)(nil), "cloud_wallet.chargeNotifyResp")
	proto.RegisterType((*DrawNotifyReq)(nil), "cloud_wallet.drawNotifyReq")
	proto.RegisterType((*DrawNotifyResp)(nil), "cloud_wallet.drawNotifyResp")
	proto.RegisterType((*IdCardRealNameAuthReq)(nil), "cloud_wallet.IdCardRealNameAuthReq")
	proto.RegisterType((*IdCardRealNameAuthResp)(nil), "cloud_wallet.IdCardRealNameAuthResp")
	proto.RegisterType((*AuthPaymentSecretReq)(nil), "cloud_wallet.authPaymentSecretReq")
	proto.RegisterType((*AuthPaymentSecretResp)(nil), "cloud_wallet.authPaymentSecretResp")
}

func init() {
	proto.RegisterFile("cloud_wallet.proto", fileDescriptor_f9de16a1887ae03b)
}

var fileDescriptor_f9de16a1887ae03b = []byte{
	// 1581 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x19, 0xcd, 0x6e, 0xdb, 0x46,
	0x13, 0x34, 0x2d, 0xd9, 0x1a, 0xff, 0xc4, 0xde, 0xd8, 0x32, 0xad, 0xe4, 0x0b, 0x1c, 0x7e, 0xfe,
	0xf2, 0x19, 0x28, 0xe0, 0x16, 0xe9, 0xa5, 0x40, 0x81, 0x00, 0xb1, 0xdc, 0x83, 0x8a, 0xc4, 0x0e,
	0xa8, 0xa4, 0x4d, 0x8b, 0x02, 0xea, 0x9a, 0x5c, 0xdb, 0x84, 0x28, 0x92, 0x59, 0x52, 0x71, 0xdc,
	0x5b, 0xd1, 0x43, 0x1f, 0xa0, 0xd7, 0xa2, 0x4f, 0x50, 0xf4, 0x01, 0x7a, 0xe8, 0xb1, 0xcf, 0x50,
	0xa0, 0xef, 0x51, 0xa0, 0xb7, 0x62, 0x7f, 0x48, 0x2d, 0x97, 0x94, 0x14, 0x45, 0x49, 0x4f, 0xd6,
	0x0c, 0x67, 0x67, 0xe7, 0x7f, 0x67, 0xc6, 0x80, 0xdc, 0x20, 0x1a, 0x7a, 0xbd, 0x2b, 0x1c, 0x04,
	0x24, 0x3d, 0x8c, 0x69, 0x94, 0x46, 0x68, 0x55, 0xc5, 0xd9, 0x0f, 0x00, 0xda, 0xd1, 0x60, 0x10,
	0x85, 0x0e, 0x49, 0x62, 0x64, 0xc1, 0x12, 0xa1, 0xb4, 0x1d, 0x79, 0xc4, 0x32, 0xf6, 0x8c, 0x83,
	0x9a, 0x93, 0x81, 0xa8, 0x09, 0x75, 0x42, 0xe9, 0xe3, 0xe4, 0xc2, 0x5a, 0xd8, 0x33, 0x0e, 0x1a,
	0x8e, 0x84, 0xec, 0x43, 0xd8, 0x7a, 0x96, 0x10, 0x7a, 0xe2, 0x46, 0xc3, 0x30, 0x7d, 0xe8, 0xf2,
	0x3f, 0x0e, 0x79, 0xc1, 0xe8, 0x87, 0x09, 0xa1, 0x1d, 0x8f, 0x33, 0x6a, 0x38, 0x12, 0xb2, 0xff,
	0x34, 0x60, 0xbb, 0xe2, 0x40, 0x12, 0x23, 0x04, 0x8b, 0x49, 0x4a, 0x62, 0x4e, 0xbf, 0xe6, 0xf0,
	0xdf, 0xa8, 0x05, 0xcb, 0x94, 0xe0, 0xe0, 0xe1, 0x30, 0xbd, 0xe4, 0xf7, 0xae, 0x39, 0x39, 0xcc,
	0x6e, 0xf0, 0xbd, 0x36, 0xa6, 0x9e, 0x65, 0x8a, 0x1b, 0x04, 0x94, 0x9d, 0x39, 0xc1, 0x03, 0x62,
	0x2d, 0xf2, 0x2f, 0x39, 0x8c, 0xf6, 0x61, 0x0d, 0x8b, 0x2b, 0xbb, 0x29, 0x4e, 0x87, 0x89, 0x55,
	0xe3, 0x4c, 0x8b, 0x48, 0xf4, 0x11, 0x80, 0x9b, 0xdb, 0xc4, 0xaa, 0xef, 0x19, 0x07, 0x2b, 0xf7,
	0xad, 0xc3, 0x82, 0x29, 0x47, 0x36, 0x73, 0x14, 0x5a, 0xfb, 0x7d, 0xa1, 0x9c, 0x54, 0xeb, 0x08,
	0x07, 0x38, 0x74, 0xc9, 0x24, 0x73, 0xa4, 0xd0, 0xac, 0x3a, 0x90, 0xc4, 0x68, 0x0f, 0x56, 0x06,
	0xd8, 0x0f, 0x25, 0x8a, 0x1f, 0x33, 0x1d, 0x15, 0xa5, 0x89, 0xb9, 0x30, 0x83, 0x98, 0x3f, 0x19,
	0x60, 0xb5, 0x19, 0xdd, 0xe7, 0x9c, 0xcc, 0x21, 0x6e, 0x44, 0xbd, 0x47, 0x7e, 0x32, 0xc9, 0x73,
	0xcc, 0x3f, 0x1e, 0x4e, 0x89, 0xf4, 0x3f, 0xff, 0xcd, 0xe2, 0x25, 0xc6, 0x17, 0xe4, 0x64, 0x38,
	0xe0, 0x4e, 0xa8, 0x39, 0x19, 0xc8, 0xbc, 0xc0, 0x7e, 0x76, 0xfd, 0x6f, 0x84, 0x17, 0x6a, 0x4e,
	0x0e, 0x33, 0xd5, 0xa2, 0x98, 0x50, 0x9c, 0xfa, 0x51, 0xd8, 0x39, 0xe6, 0x3e, 0x68, 0x38, 0x2a,
	0xca, 0xfe, 0xce, 0x80, 0xdd, 0x31, 0x02, 0x26, 0xf1, 0x58, 0x09, 0xb7, 0xa0, 0x96, 0x46, 0x29,
	0x0e, 0xb8, 0x88, 0x35, 0x47, 0x00, 0xcc, 0x4c, 0x34, 0x3f, 0x6f, 0x99, 0x7b, 0x66, 0xd9, 0x4c,
	0x0a, 0x7f, 0x85, 0xd6, 0xfe, 0xd9, 0x00, 0x18, 0x7d, 0x9a, 0x64, 0x98, 0xf4, 0x3a, 0x26, 0xf2,
	0x56, 0xfe, 0x9b, 0xd1, 0xe2, 0x01, 0x73, 0x29, 0xb7, 0xcb, 0x82, 0x23, 0x21, 0xa6, 0x3a, 0x3e,
	0x4f, 0x09, 0x7d, 0x28, 0x3e, 0x2e, 0xf2, 0x8f, 0x2a, 0x8a, 0x51, 0xb8, 0x94, 0xe0, 0x94, 0x78,
	0x4f, 0xfd, 0x01, 0xe1, 0xc6, 0x31, 0x1d, 0x15, 0xc5, 0x78, 0x53, 0x32, 0xc0, 0xb4, 0xcf, 0x43,
	0xb3, 0xe1, 0x48, 0xc8, 0xfe, 0x00, 0x9a, 0x17, 0x24, 0x65, 0xe1, 0x74, 0x84, 0xc3, 0xbe, 0x8b,
	0xa7, 0xba, 0xd4, 0x7e, 0x01, 0x3b, 0x95, 0x27, 0x26, 0xd8, 0xf8, 0x01, 0xac, 0x9e, 0xe1, 0xb0,
	0xcf, 0x32, 0xad, 0x13, 0x9e, 0x47, 0xd6, 0x02, 0xb7, 0x67, 0xab, 0x68, 0xcf, 0x23, 0x85, 0xc2,
	0x29, 0xd0, 0xdb, 0xbf, 0x1a, 0xb0, 0xaa, 0x7e, 0x46, 0x77, 0x00, 0x72, 0x82, 0x63, 0x19, 0xe6,
	0x0a, 0x06, 0xdd, 0x86, 0x06, 0x13, 0xec, 0xf4, 0x2a, 0x24, 0x54, 0xc6, 0xde, 0x08, 0x81, 0xec,
	0x91, 0x38, 0x4f, 0x99, 0x0f, 0x44, 0x14, 0x16, 0x70, 0xe8, 0x1e, 0xac, 0x67, 0xf0, 0xc9, 0x70,
	0x70, 0x46, 0xa8, 0x2c, 0x0b, 0x1a, 0xb6, 0xca, 0xf2, 0x8d, 0x82, 0xe5, 0xed, 0x5f, 0x0c, 0x40,
	0xd8, 0xf3, 0x54, 0x83, 0x4d, 0xca, 0x98, 0x7f, 0x4f, 0xf4, 0x26, 0xd4, 0x07, 0xd1, 0x99, 0x1f,
	0x64, 0x52, 0x4b, 0xc8, 0x3e, 0x85, 0x9b, 0x25, 0x79, 0x93, 0x58, 0xab, 0x1c, 0xc6, 0x0c, 0x95,
	0x63, 0x08, 0x37, 0xbb, 0x24, 0x7d, 0x82, 0xaf, 0x07, 0x24, 0x4c, 0xbb, 0xc4, 0xa5, 0x64, 0x62,
	0xcd, 0xd8, 0x87, 0xb5, 0x58, 0xa5, 0xe5, 0x56, 0x30, 0x9d, 0x22, 0x52, 0xaf, 0x07, 0x66, 0xb9,
	0x1e, 0x3c, 0x81, 0xad, 0xf2, 0xb5, 0x73, 0x29, 0xf2, 0x1c, 0x2c, 0x26, 0x63, 0x81, 0x25, 0x7b,
	0x56, 0x66, 0xd6, 0xa6, 0xa1, 0x69, 0x63, 0x3f, 0x83, 0xdd, 0x31, 0x9c, 0xe7, 0x12, 0xf8, 0x0c,
	0x36, 0xdc, 0x4b, 0x4c, 0x2f, 0xc8, 0xf4, 0x47, 0x56, 0xcb, 0x29, 0x21, 0xa5, 0x9a, 0x53, 0xc5,
	0xea, 0x64, 0x66, 0xd5, 0xc9, 0x26, 0xb0, 0xa9, 0xdd, 0x21, 0x2a, 0x81, 0x24, 0x36, 0x54, 0xe2,
	0x39, 0x9e, 0x9f, 0xaf, 0x61, 0xdd, 0xa3, 0xf8, 0xea, 0x1d, 0x2a, 0xe2, 0xc2, 0x8d, 0xc2, 0x0d,
	0xef, 0x44, 0x8d, 0x3f, 0x0c, 0xd8, 0x48, 0x48, 0xe8, 0x39, 0xc4, 0x7b, 0x82, 0xdd, 0x3e, 0x99,
	0xa6, 0x89, 0x20, 0x7a, 0x3a, 0x7a, 0x2a, 0x14, 0x0c, 0x7b, 0x49, 0x3b, 0xc9, 0xa3, 0xa1, 0xdb,
	0xbf, 0xce, 0x5e, 0x52, 0x09, 0xb2, 0xec, 0xe8, 0x24, 0x9f, 0xbc, 0x72, 0x83, 0x61, 0xe2, 0xbf,
	0xcc, 0x1e, 0x53, 0x15, 0xc5, 0x28, 0x24, 0x27, 0x3f, 0xcd, 0x4b, 0x80, 0x8a, 0x62, 0x52, 0xc9,
	0x17, 0xa7, 0x2e, 0x9e, 0x23, 0xf9, 0xd8, 0x34, 0xa1, 0x2e, 0xeb, 0xca, 0x12, 0x67, 0x2b, 0x21,
	0x3b, 0x82, 0x4d, 0x4d, 0x33, 0xd1, 0x91, 0xd0, 0x0c, 0x21, 0x4b, 0x75, 0xcd, 0x51, 0x51, 0x73,
	0xd8, 0xf2, 0x2f, 0x03, 0x36, 0xe4, 0x6d, 0xac, 0x81, 0x88, 0x52, 0xff, 0xfc, 0x7a, 0xac, 0x2d,
	0xf7, 0x60, 0xc5, 0x51, 0x04, 0x11, 0x35, 0x45, 0x45, 0xb1, 0xee, 0xa3, 0x4b, 0x42, 0x51, 0xc7,
	0x45, 0x64, 0xe4, 0xb0, 0x6e, 0xad, 0xc5, 0xb2, 0xb5, 0x8a, 0xbe, 0xaa, 0x95, 0x7c, 0xa5, 0x79,
	0xa4, 0x5e, 0xf6, 0xc8, 0x01, 0xdc, 0xc8, 0x01, 0x56, 0x7d, 0x3b, 0xc7, 0xdc, 0xc0, 0xa6, 0xa3,
	0xa3, 0x6d, 0x1f, 0x76, 0x46, 0x7a, 0xb7, 0x03, 0xdf, 0xed, 0x13, 0x4f, 0xaa, 0xdf, 0x82, 0xe5,
	0x82, 0xb1, 0x4d, 0x67, 0x59, 0x55, 0x90, 0x77, 0xd1, 0xac, 0xc9, 0x15, 0x69, 0x91, 0xc3, 0x4a,
	0x7f, 0x60, 0x16, 0xfa, 0x83, 0xc7, 0xb0, 0xe9, 0xb2, 0x0b, 0x5e, 0x2b, 0x5e, 0x35, 0x67, 0x2f,
	0x94, 0x9c, 0x6d, 0xff, 0x66, 0xb0, 0xf1, 0xa2, 0xc8, 0x6f, 0x42, 0xe3, 0x50, 0xc1, 0xb0, 0x51,
	0x8c, 0x9e, 0x62, 0x32, 0x37, 0xf2, 0x0c, 0xbd, 0x0d, 0x0d, 0x3f, 0x71, 0x88, 0x4b, 0x46, 0xe1,
	0x3f, 0x42, 0x68, 0x31, 0x57, 0x9b, 0x21, 0xe6, 0x4e, 0xe1, 0xe6, 0x05, 0x13, 0x3a, 0x93, 0x80,
	0x35, 0x2b, 0xb3, 0x59, 0xa4, 0xa8, 0x80, 0xfd, 0x83, 0x09, 0x5b, 0x65, 0x8e, 0x13, 0x6c, 0x72,
	0x07, 0x20, 0x2e, 0x15, 0x85, 0x11, 0x06, 0xed, 0xc2, 0xb2, 0x9f, 0xf4, 0x02, 0xb5, 0x2a, 0xf8,
	0xb2, 0x2a, 0xdc, 0x85, 0x55, 0x3f, 0xe9, 0x11, 0xbd, 0x2c, 0xf8, 0xc5, 0x20, 0x24, 0x5a, 0x10,
	0x8a, 0x58, 0xd6, 0xd1, 0x8c, 0x99, 0xb8, 0xb5, 0x97, 0xf2, 0x9c, 0x10, 0x7d, 0xe5, 0x4a, 0x5c,
	0xac, 0x20, 0xd2, 0x39, 0x4b, 0x85, 0x86, 0xb6, 0x09, 0xf5, 0x50, 0x54, 0x90, 0x65, 0x51, 0x41,
	0x04, 0xc4, 0x54, 0x23, 0xaf, 0x62, 0x9f, 0x12, 0x9e, 0x83, 0x0d, 0x51, 0xb9, 0x47, 0x18, 0x74,
	0x08, 0x28, 0xf7, 0x61, 0x3b, 0x1a, 0xc4, 0x01, 0x49, 0x89, 0x67, 0x01, 0xe7, 0x5d, 0xf1, 0x45,
	0x73, 0xf3, 0xca, 0x0c, 0x6e, 0xee, 0xc2, 0x4e, 0xee, 0x24, 0x9e, 0x60, 0xc7, 0x24, 0xc5, 0x7e,
	0x30, 0x9f, 0xab, 0x7f, 0x34, 0x60, 0xab, 0x8a, 0xeb, 0x58, 0x96, 0x2d, 0x58, 0x0e, 0x7d, 0xb7,
	0x1f, 0x2a, 0x09, 0x9b, 0xc1, 0xdc, 0xb6, 0x2f, 0x71, 0x4a, 0x68, 0x1e, 0xf8, 0x1c, 0xd2, 0xc5,
	0x58, 0xe4, 0xb3, 0xea, 0x98, 0x94, 0xa9, 0xa9, 0x5e, 0x61, 0x93, 0x8b, 0x55, 0xad, 0x74, 0x12,
	0xa3, 0xcf, 0xaa, 0x45, 0xb7, 0x0c, 0xde, 0xca, 0xdb, 0x45, 0xa3, 0x56, 0x72, 0xa9, 0x56, 0xfd,
	0xcd, 0xab, 0xff, 0x31, 0x34, 0x03, 0x3e, 0x78, 0xe4, 0x85, 0x84, 0x0d, 0x5d, 0x33, 0x0e, 0xa3,
	0xf6, 0xb7, 0x0b, 0xb0, 0x53, 0xc9, 0x66, 0x42, 0x06, 0xbe, 0x1b, 0xb7, 0xdc, 0x83, 0xf5, 0x1c,
	0x54, 0xdf, 0x64, 0x0d, 0xab, 0xb8, 0xaf, 0x5e, 0x48, 0xaa, 0xa2, 0x25, 0x97, 0x66, 0xb0, 0x64,
	0x1f, 0x6e, 0xb9, 0x51, 0x78, 0xee, 0xd3, 0x41, 0x57, 0x7d, 0xbf, 0xdb, 0x91, 0x47, 0xe6, 0x0a,
	0x78, 0x66, 0x70, 0x37, 0xf2, 0x88, 0x34, 0x05, 0xff, 0x6d, 0x3f, 0x87, 0xdb, 0xe3, 0x2f, 0x9b,
	0xab, 0xd9, 0xc5, 0x70, 0x43, 0x34, 0xa2, 0xe2, 0x29, 0x7c, 0x7b, 0x2d, 0x62, 0xfe, 0xaa, 0xd8,
	0x8f, 0xb2, 0x7e, 0x3a, 0xbb, 0x62, 0x2e, 0x81, 0x7f, 0x37, 0x60, 0x8d, 0x75, 0x9c, 0x23, 0x79,
	0x77, 0x61, 0x39, 0xa2, 0x1e, 0xa1, 0xbd, 0x30, 0x92, 0x12, 0x2f, 0x71, 0xf8, 0x24, 0x42, 0xfb,
	0xb0, 0x9e, 0x5e, 0xfa, 0xd4, 0xeb, 0xe5, 0x04, 0x42, 0xec, 0x55, 0x8e, 0x3d, 0x95, 0x54, 0x07,
	0xb0, 0xc1, 0xd4, 0xe8, 0xb1, 0xa9, 0xad, 0x27, 0x6b, 0xac, 0x59, 0x39, 0xfd, 0xbd, 0x07, 0x9b,
	0x57, 0x7e, 0x7a, 0xc9, 0xee, 0xc7, 0x41, 0x0f, 0xab, 0xab, 0x85, 0x8d, 0xd1, 0x07, 0xd9, 0xf2,
	0xfd, 0x07, 0x80, 0x73, 0x8c, 0xf8, 0x54, 0x5a, 0xd3, 0xa6, 0x52, 0xfb, 0x53, 0xd1, 0x9b, 0xbf,
	0x15, 0xa3, 0x7c, 0x6f, 0xc0, 0x76, 0x87, 0x2f, 0xe5, 0x1c, 0xb9, 0x80, 0x9b, 0x36, 0x61, 0xed,
	0xc0, 0x92, 0xef, 0x71, 0x8d, 0xb3, 0x35, 0xa3, 0x5c, 0xea, 0xdd, 0x82, 0x06, 0x25, 0x38, 0xe8,
	0xf1, 0x44, 0x35, 0xb5, 0xad, 0x9e, 0x36, 0x3f, 0x2e, 0x96, 0xe7, 0xc7, 0x73, 0x68, 0x56, 0x09,
	0x32, 0x66, 0xeb, 0xf8, 0xe6, 0x85, 0xec, 0x19, 0x6c, 0xe1, 0x61, 0x7a, 0xf9, 0xda, 0xf3, 0xf1,
	0xff, 0x60, 0x5d, 0x0e, 0x8f, 0xbd, 0x64, 0xc2, 0x48, 0x49, 0x60, 0xbb, 0x82, 0xed, 0xdb, 0x96,
	0xfe, 0xfe, 0xdf, 0x26, 0x20, 0x65, 0xeb, 0xd6, 0x25, 0xf4, 0xa5, 0xef, 0x12, 0xf4, 0x15, 0x6c,
	0x96, 0x36, 0xb6, 0x48, 0x7b, 0x26, 0xaa, 0x76, 0xc0, 0xad, 0xff, 0x4e, 0xa5, 0x49, 0x62, 0xd4,
	0x03, 0x54, 0x76, 0x0d, 0xd2, 0x8e, 0x56, 0x46, 0x51, 0x6b, 0x7f, 0x3a, 0x51, 0x12, 0xa3, 0x2f,
	0x60, 0x43, 0xdf, 0x1d, 0xa0, 0xbb, 0xc5, 0x93, 0x15, 0x2b, 0x8d, 0x96, 0x3d, 0x8d, 0x44, 0xc8,
	0x5e, 0xde, 0xde, 0xa2, 0x0a, 0xb5, 0x4b, 0x0b, 0x61, 0x5d, 0xf6, 0x31, 0x4b, 0xe0, 0x4b, 0xd8,
	0xae, 0x5c, 0x83, 0xa2, 0x7b, 0x9a, 0x43, 0xc7, 0x2c, 0x73, 0x5b, 0xff, 0x7f, 0x2d, 0xba, 0x24,
	0x3e, 0xda, 0xf8, 0x72, 0xfd, 0xf0, 0x63, 0x95, 0xf6, 0xac, 0xce, 0xff, 0x5d, 0xf0, 0xe1, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x41, 0xcf, 0xe9, 0x6d, 0x44, 0x18, 0x00, 0x00,
}
