// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.11.4
// source: cloud_wallet.proto

package cloud_wallet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CloudWalletService_UserNcountAccount_FullMethodName       = "/cloud_wallet.CloudWalletService/UserNcountAccount"
	CloudWalletService_IdCardRealNameAuth_FullMethodName      = "/cloud_wallet.CloudWalletService/IdCardRealNameAuth"
	CloudWalletService_SetPaymentSecret_FullMethodName        = "/cloud_wallet.CloudWalletService/SetPaymentSecret"
	CloudWalletService_CloudWalletRecordList_FullMethodName   = "/cloud_wallet.CloudWalletService/CloudWalletRecordList"
	CloudWalletService_BindUserBankcard_FullMethodName        = "/cloud_wallet.CloudWalletService/BindUserBankcard"
	CloudWalletService_BindUserBankcardConfirm_FullMethodName = "/cloud_wallet.CloudWalletService/BindUserBankcardConfirm"
	CloudWalletService_UnBindingUserBankcard_FullMethodName   = "/cloud_wallet.CloudWalletService/UnBindingUserBankcard"
	CloudWalletService_UserRecharge_FullMethodName            = "/cloud_wallet.CloudWalletService/UserRecharge"
	CloudWalletService_UserWithdrawal_FullMethodName          = "/cloud_wallet.CloudWalletService/UserWithdrawal"
	CloudWalletService_ChargeNotify_FullMethodName            = "/cloud_wallet.CloudWalletService/ChargeNotify"
	CloudWalletService_WithDrawNotify_FullMethodName          = "/cloud_wallet.CloudWalletService/WithDrawNotify"
	CloudWalletService_SendRedPacket_FullMethodName           = "/cloud_wallet.CloudWalletService/SendRedPacket"
	CloudWalletService_ClickRedPacket_FullMethodName          = "/cloud_wallet.CloudWalletService/ClickRedPacket"
)

// CloudWalletServiceClient is the client API for CloudWalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CloudWalletServiceClient interface {
	// ==================================云钱包管理 ========
	// 获取云账户信息
	UserNcountAccount(ctx context.Context, in *UserNcountAccountReq, opts ...grpc.CallOption) (*UserNcountAccountResp, error)
	// 身份证实名认证
	IdCardRealNameAuth(ctx context.Context, in *IdCardRealNameAuthReq, opts ...grpc.CallOption) (*IdCardRealNameAuthResp, error)
	// 设置用户支付密码
	SetPaymentSecret(ctx context.Context, in *SetPaymentSecretReq, opts ...grpc.CallOption) (*SetPaymentSecretResp, error)
	// 云钱包收支明细
	CloudWalletRecordList(ctx context.Context, in *CloudWalletRecordListReq, opts ...grpc.CallOption) (*CloudWalletRecordListResp, error)
	//绑定用户银行卡
	BindUserBankcard(ctx context.Context, in *BindUserBankcardReq, opts ...grpc.CallOption) (*BindUserBankcardResp, error)
	//绑定用户银行卡确认code
	BindUserBankcardConfirm(ctx context.Context, in *BindUserBankcardConfirmReq, opts ...grpc.CallOption) (*BindUserBankcardConfirmResp, error)
	//解绑用户银行卡
	UnBindingUserBankcard(ctx context.Context, in *UnBindingUserBankcardReq, opts ...grpc.CallOption) (*UnBindingUserBankcardResp, error)
	// 银行卡充值
	UserRecharge(ctx context.Context, in *UserRechargeReq, opts ...grpc.CallOption) (*UserRechargeResp, error)
	// 银行卡提现
	UserWithdrawal(ctx context.Context, in *DrawAccountReq, opts ...grpc.CallOption) (*DrawAccountResp, error)
	// 充值回调接口
	ChargeNotify(ctx context.Context, in *ChargeNotifyReq, opts ...grpc.CallOption) (*ChargeNotifyResp, error)
	// 提现回调接口
	WithDrawNotify(ctx context.Context, in *DrawNotifyReq, opts ...grpc.CallOption) (*DrawNotifyResp, error)
	// 发送红包接口
	SendRedPacket(ctx context.Context, in *SendRedPacketReq, opts ...grpc.CallOption) (*SendRedPacketResp, error)
	// 抢红包接口
	ClickRedPacket(ctx context.Context, in *ClickRedPacketReq, opts ...grpc.CallOption) (*ClickRedPacketResp, error)
}

type cloudWalletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudWalletServiceClient(cc grpc.ClientConnInterface) CloudWalletServiceClient {
	return &cloudWalletServiceClient{cc}
}

func (c *cloudWalletServiceClient) UserNcountAccount(ctx context.Context, in *UserNcountAccountReq, opts ...grpc.CallOption) (*UserNcountAccountResp, error) {
	out := new(UserNcountAccountResp)
	err := c.cc.Invoke(ctx, CloudWalletService_UserNcountAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWalletServiceClient) IdCardRealNameAuth(ctx context.Context, in *IdCardRealNameAuthReq, opts ...grpc.CallOption) (*IdCardRealNameAuthResp, error) {
	out := new(IdCardRealNameAuthResp)
	err := c.cc.Invoke(ctx, CloudWalletService_IdCardRealNameAuth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWalletServiceClient) SetPaymentSecret(ctx context.Context, in *SetPaymentSecretReq, opts ...grpc.CallOption) (*SetPaymentSecretResp, error) {
	out := new(SetPaymentSecretResp)
	err := c.cc.Invoke(ctx, CloudWalletService_SetPaymentSecret_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWalletServiceClient) CloudWalletRecordList(ctx context.Context, in *CloudWalletRecordListReq, opts ...grpc.CallOption) (*CloudWalletRecordListResp, error) {
	out := new(CloudWalletRecordListResp)
	err := c.cc.Invoke(ctx, CloudWalletService_CloudWalletRecordList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWalletServiceClient) BindUserBankcard(ctx context.Context, in *BindUserBankcardReq, opts ...grpc.CallOption) (*BindUserBankcardResp, error) {
	out := new(BindUserBankcardResp)
	err := c.cc.Invoke(ctx, CloudWalletService_BindUserBankcard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWalletServiceClient) BindUserBankcardConfirm(ctx context.Context, in *BindUserBankcardConfirmReq, opts ...grpc.CallOption) (*BindUserBankcardConfirmResp, error) {
	out := new(BindUserBankcardConfirmResp)
	err := c.cc.Invoke(ctx, CloudWalletService_BindUserBankcardConfirm_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWalletServiceClient) UnBindingUserBankcard(ctx context.Context, in *UnBindingUserBankcardReq, opts ...grpc.CallOption) (*UnBindingUserBankcardResp, error) {
	out := new(UnBindingUserBankcardResp)
	err := c.cc.Invoke(ctx, CloudWalletService_UnBindingUserBankcard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWalletServiceClient) UserRecharge(ctx context.Context, in *UserRechargeReq, opts ...grpc.CallOption) (*UserRechargeResp, error) {
	out := new(UserRechargeResp)
	err := c.cc.Invoke(ctx, CloudWalletService_UserRecharge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWalletServiceClient) UserWithdrawal(ctx context.Context, in *DrawAccountReq, opts ...grpc.CallOption) (*DrawAccountResp, error) {
	out := new(DrawAccountResp)
	err := c.cc.Invoke(ctx, CloudWalletService_UserWithdrawal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWalletServiceClient) ChargeNotify(ctx context.Context, in *ChargeNotifyReq, opts ...grpc.CallOption) (*ChargeNotifyResp, error) {
	out := new(ChargeNotifyResp)
	err := c.cc.Invoke(ctx, CloudWalletService_ChargeNotify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWalletServiceClient) WithDrawNotify(ctx context.Context, in *DrawNotifyReq, opts ...grpc.CallOption) (*DrawNotifyResp, error) {
	out := new(DrawNotifyResp)
	err := c.cc.Invoke(ctx, CloudWalletService_WithDrawNotify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWalletServiceClient) SendRedPacket(ctx context.Context, in *SendRedPacketReq, opts ...grpc.CallOption) (*SendRedPacketResp, error) {
	out := new(SendRedPacketResp)
	err := c.cc.Invoke(ctx, CloudWalletService_SendRedPacket_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cloudWalletServiceClient) ClickRedPacket(ctx context.Context, in *ClickRedPacketReq, opts ...grpc.CallOption) (*ClickRedPacketResp, error) {
	out := new(ClickRedPacketResp)
	err := c.cc.Invoke(ctx, CloudWalletService_ClickRedPacket_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudWalletServiceServer is the server API for CloudWalletService service.
// All implementations must embed UnimplementedCloudWalletServiceServer
// for forward compatibility
type CloudWalletServiceServer interface {
	// ==================================云钱包管理 ========
	// 获取云账户信息
	UserNcountAccount(context.Context, *UserNcountAccountReq) (*UserNcountAccountResp, error)
	// 身份证实名认证
	IdCardRealNameAuth(context.Context, *IdCardRealNameAuthReq) (*IdCardRealNameAuthResp, error)
	// 设置用户支付密码
	SetPaymentSecret(context.Context, *SetPaymentSecretReq) (*SetPaymentSecretResp, error)
	// 云钱包收支明细
	CloudWalletRecordList(context.Context, *CloudWalletRecordListReq) (*CloudWalletRecordListResp, error)
	//绑定用户银行卡
	BindUserBankcard(context.Context, *BindUserBankcardReq) (*BindUserBankcardResp, error)
	//绑定用户银行卡确认code
	BindUserBankcardConfirm(context.Context, *BindUserBankcardConfirmReq) (*BindUserBankcardConfirmResp, error)
	//解绑用户银行卡
	UnBindingUserBankcard(context.Context, *UnBindingUserBankcardReq) (*UnBindingUserBankcardResp, error)
	// 银行卡充值
	UserRecharge(context.Context, *UserRechargeReq) (*UserRechargeResp, error)
	// 银行卡提现
	UserWithdrawal(context.Context, *DrawAccountReq) (*DrawAccountResp, error)
	// 充值回调接口
	ChargeNotify(context.Context, *ChargeNotifyReq) (*ChargeNotifyResp, error)
	// 提现回调接口
	WithDrawNotify(context.Context, *DrawNotifyReq) (*DrawNotifyResp, error)
	// 发送红包接口
	SendRedPacket(context.Context, *SendRedPacketReq) (*SendRedPacketResp, error)
	// 抢红包接口
	ClickRedPacket(context.Context, *ClickRedPacketReq) (*ClickRedPacketResp, error)
	mustEmbedUnimplementedCloudWalletServiceServer()
}

// UnimplementedCloudWalletServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCloudWalletServiceServer struct {
}

func (UnimplementedCloudWalletServiceServer) UserNcountAccount(context.Context, *UserNcountAccountReq) (*UserNcountAccountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserNcountAccount not implemented")
}
func (UnimplementedCloudWalletServiceServer) IdCardRealNameAuth(context.Context, *IdCardRealNameAuthReq) (*IdCardRealNameAuthResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IdCardRealNameAuth not implemented")
}
func (UnimplementedCloudWalletServiceServer) SetPaymentSecret(context.Context, *SetPaymentSecretReq) (*SetPaymentSecretResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPaymentSecret not implemented")
}
func (UnimplementedCloudWalletServiceServer) CloudWalletRecordList(context.Context, *CloudWalletRecordListReq) (*CloudWalletRecordListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloudWalletRecordList not implemented")
}
func (UnimplementedCloudWalletServiceServer) BindUserBankcard(context.Context, *BindUserBankcardReq) (*BindUserBankcardResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindUserBankcard not implemented")
}
func (UnimplementedCloudWalletServiceServer) BindUserBankcardConfirm(context.Context, *BindUserBankcardConfirmReq) (*BindUserBankcardConfirmResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindUserBankcardConfirm not implemented")
}
func (UnimplementedCloudWalletServiceServer) UnBindingUserBankcard(context.Context, *UnBindingUserBankcardReq) (*UnBindingUserBankcardResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnBindingUserBankcard not implemented")
}
func (UnimplementedCloudWalletServiceServer) UserRecharge(context.Context, *UserRechargeReq) (*UserRechargeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRecharge not implemented")
}
func (UnimplementedCloudWalletServiceServer) UserWithdrawal(context.Context, *DrawAccountReq) (*DrawAccountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserWithdrawal not implemented")
}
func (UnimplementedCloudWalletServiceServer) ChargeNotify(context.Context, *ChargeNotifyReq) (*ChargeNotifyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChargeNotify not implemented")
}
func (UnimplementedCloudWalletServiceServer) WithDrawNotify(context.Context, *DrawNotifyReq) (*DrawNotifyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithDrawNotify not implemented")
}
func (UnimplementedCloudWalletServiceServer) SendRedPacket(context.Context, *SendRedPacketReq) (*SendRedPacketResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRedPacket not implemented")
}
func (UnimplementedCloudWalletServiceServer) ClickRedPacket(context.Context, *ClickRedPacketReq) (*ClickRedPacketResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClickRedPacket not implemented")
}
func (UnimplementedCloudWalletServiceServer) mustEmbedUnimplementedCloudWalletServiceServer() {}

// UnsafeCloudWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudWalletServiceServer will
// result in compilation errors.
type UnsafeCloudWalletServiceServer interface {
	mustEmbedUnimplementedCloudWalletServiceServer()
}

func RegisterCloudWalletServiceServer(s grpc.ServiceRegistrar, srv CloudWalletServiceServer) {
	s.RegisterService(&CloudWalletService_ServiceDesc, srv)
}

func _CloudWalletService_UserNcountAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserNcountAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWalletServiceServer).UserNcountAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWalletService_UserNcountAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWalletServiceServer).UserNcountAccount(ctx, req.(*UserNcountAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWalletService_IdCardRealNameAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdCardRealNameAuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWalletServiceServer).IdCardRealNameAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWalletService_IdCardRealNameAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWalletServiceServer).IdCardRealNameAuth(ctx, req.(*IdCardRealNameAuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWalletService_SetPaymentSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPaymentSecretReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWalletServiceServer).SetPaymentSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWalletService_SetPaymentSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWalletServiceServer).SetPaymentSecret(ctx, req.(*SetPaymentSecretReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWalletService_CloudWalletRecordList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudWalletRecordListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWalletServiceServer).CloudWalletRecordList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWalletService_CloudWalletRecordList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWalletServiceServer).CloudWalletRecordList(ctx, req.(*CloudWalletRecordListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWalletService_BindUserBankcard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindUserBankcardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWalletServiceServer).BindUserBankcard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWalletService_BindUserBankcard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWalletServiceServer).BindUserBankcard(ctx, req.(*BindUserBankcardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWalletService_BindUserBankcardConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindUserBankcardConfirmReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWalletServiceServer).BindUserBankcardConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWalletService_BindUserBankcardConfirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWalletServiceServer).BindUserBankcardConfirm(ctx, req.(*BindUserBankcardConfirmReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWalletService_UnBindingUserBankcard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnBindingUserBankcardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWalletServiceServer).UnBindingUserBankcard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWalletService_UnBindingUserBankcard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWalletServiceServer).UnBindingUserBankcard(ctx, req.(*UnBindingUserBankcardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWalletService_UserRecharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRechargeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWalletServiceServer).UserRecharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWalletService_UserRecharge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWalletServiceServer).UserRecharge(ctx, req.(*UserRechargeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWalletService_UserWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrawAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWalletServiceServer).UserWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWalletService_UserWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWalletServiceServer).UserWithdrawal(ctx, req.(*DrawAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWalletService_ChargeNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeNotifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWalletServiceServer).ChargeNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWalletService_ChargeNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWalletServiceServer).ChargeNotify(ctx, req.(*ChargeNotifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWalletService_WithDrawNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrawNotifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWalletServiceServer).WithDrawNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWalletService_WithDrawNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWalletServiceServer).WithDrawNotify(ctx, req.(*DrawNotifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWalletService_SendRedPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRedPacketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWalletServiceServer).SendRedPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWalletService_SendRedPacket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWalletServiceServer).SendRedPacket(ctx, req.(*SendRedPacketReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CloudWalletService_ClickRedPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickRedPacketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudWalletServiceServer).ClickRedPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CloudWalletService_ClickRedPacket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudWalletServiceServer).ClickRedPacket(ctx, req.(*ClickRedPacketReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudWalletService_ServiceDesc is the grpc.ServiceDesc for CloudWalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudWalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloud_wallet.CloudWalletService",
	HandlerType: (*CloudWalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserNcountAccount",
			Handler:    _CloudWalletService_UserNcountAccount_Handler,
		},
		{
			MethodName: "IdCardRealNameAuth",
			Handler:    _CloudWalletService_IdCardRealNameAuth_Handler,
		},
		{
			MethodName: "SetPaymentSecret",
			Handler:    _CloudWalletService_SetPaymentSecret_Handler,
		},
		{
			MethodName: "CloudWalletRecordList",
			Handler:    _CloudWalletService_CloudWalletRecordList_Handler,
		},
		{
			MethodName: "BindUserBankcard",
			Handler:    _CloudWalletService_BindUserBankcard_Handler,
		},
		{
			MethodName: "BindUserBankcardConfirm",
			Handler:    _CloudWalletService_BindUserBankcardConfirm_Handler,
		},
		{
			MethodName: "UnBindingUserBankcard",
			Handler:    _CloudWalletService_UnBindingUserBankcard_Handler,
		},
		{
			MethodName: "UserRecharge",
			Handler:    _CloudWalletService_UserRecharge_Handler,
		},
		{
			MethodName: "UserWithdrawal",
			Handler:    _CloudWalletService_UserWithdrawal_Handler,
		},
		{
			MethodName: "ChargeNotify",
			Handler:    _CloudWalletService_ChargeNotify_Handler,
		},
		{
			MethodName: "WithDrawNotify",
			Handler:    _CloudWalletService_WithDrawNotify_Handler,
		},
		{
			MethodName: "SendRedPacket",
			Handler:    _CloudWalletService_SendRedPacket_Handler,
		},
		{
			MethodName: "ClickRedPacket",
			Handler:    _CloudWalletService_ClickRedPacket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cloud_wallet.proto",
}
